---
title: "Imputing of missing notifications data"
author: "Richard T. Gray"
date: '`r format(Sys.Date(), format="%d %B %Y")`'
output: 
  word_document:
    pandoc_args: --output="docs/Duplicate_analysis.docx"
---

This document contains the scripts for producing imputed data sets that 
fill in missing data in HIV notifications for the Australian HIV cascade 
calculations. The script produces 10 imputed sets containing the key 
variables required for the calculations. 

```{r knitr_options, include=FALSE} 
knitr::opts_chunk$set(echo = FALSE, 
  warning = FALSE, 
  message = FALSE, 
  include = FALSE) 
```

## Methodology 

```{r Initilization}
# Open as a project (setting working directory to source and restarting R)

# Setup directories
basePath <- getwd()
Rcode <- file.path(dirname(basePath), "code") # All cascades code
HIVcode <- file.path(basePath, "code") 
dataFolder <- file.path(basePath, "data")

# Notifications folder is a private secure folder 
notificationsFolder <- file.path("/", "SVR-NAS", "Public", "SERP", "Data", 
  "National HIV Registry", "Cascades")

# Store imputed sets in the notifications folder
outputFolder <- notificationsFolder

# Load libraries and standard functions
source(file.path(Rcode, "LoadLibrary.R"))
LoadLibrary(tidyverse)
LoadLibrary(cowplot)
LoadLibrary(captioner)
LoadLibrary(scales)
source(file.path(Rcode, "FormatData.R"))


# Script options
dataYear <- 2022

runImpute <- TRUE
saveImpute <- TRUE # Save as ImputeSets.Rd in setsPath directory. 
# This file is loaded if runImpute <- FALSE

runChecks <- TRUE
changeFemaleMsm <- TRUE

```

```{r Load and clean notifications}
# This chunk loads the national notifications and does final cleaning 
# of notifications in prepartion for imputing

# Function to tidy notifications
source(file.path(Rcode, "AgeCat.R"))
source(file.path(HIVcode, "TidyNotifications.R"))

# Load cleaned notifications data
origHivData <- read_csv(file.path(notificationsFolder,
  paste0("cascadeHIVnotifications-clean-", toString(dataYear), ".csv")),
  col_types = cols(
    .default = col_integer(),
    state = col_character(),
    sex = col_character(),
    dob = col_date(format = ""),
    rob = col_character(),
    datediagnosis = col_date(format = ""),
    dateaids = col_date(format = ""),
    exposure = col_character(),
    dateneg = col_date(format = ""),
    dateindet = col_date(format = ""),
    dateill = col_date(format = ""),
    datedeath = col_date(format = ""),
    cd4date = col_date(format = ""),
    linked = col_character(),
    expgroup = col_character(),
    countrygroup = col_character(),
    aboriggroup = col_character()
  )) 

# Read in country code data
countryCodes <- read_csv(file.path(dataFolder, "countryRegionCodes.csv"),
  col_types = cols(
    COUNTRY_NAME = col_character(),
    REGION = col_character(),
    COUNTRY_CODE = col_integer(),
    REGION_CODE = col_integer()
  )) 

# Read in location of diagnosis coding
regionCodes <- read_csv(file.path(dataFolder, "postcodeRegionCodes.csv"),
  col_types = cols(
    postcode = col_integer(),
    SA3_code = col_integer(),
    SA3_name_2016 = col_character()
  ))

# Tidy up notifications for calculations
hivData <- TidyNotifications(origHivData, dataYear, countryCodes,
  regionCodes) %>% filter(yearhiv <= dataYear)

# Data checks-------------------------------------------------------------

# Quick check that we are not doing analysis outside of the data
if (max(hivData$yeardiagnosis) < dataYear) {
  stop("No data specified for final year of analysis.")
}

# HIV data variables------------------------------------------------------

# Setup variables for overarching analysis                  
allYears <- min(hivData$yeardiagnosis):dataYear # all years of data

```

```{r Set-up imputation}
# This chunk sets-up the various things for the imputation

# HIV notifications variable names for imputation and for other aspects of 
# the cascade calculations. NOTE: globalregion, countrygroup, and agebin
# need to be updated after imputation as they are based on imputed
# variables 
impVars <- c("yeardiagnosis", "state", "diag_region", "sex", "cob",
  "agehiv", "expgroup")
otherVars <- c("dob", "cd4bin", "cd4London", "yearaids", "typediagnosis",
  "aboriggroup", "yeardeath", "globalregion",
  "countrygroup", "agebin", "dateill", "previ_diag_overseas")

# Create directory for storing imputed sets
setsPath <- file.path(outputFolder,
  paste0("cascadeImputedHIVnotifications-", toString(dataYear)))
dir.create(setsPath, showWarnings = FALSE, recursive = TRUE)

# Imputed sets file string
saveStringDetails <- file.path(setsPath, "imputedHIVset")

```

```{r Create imputing data set}
# This chunk creates the final data set for imputing. Selecting the 
# variables, making sure impute character variables are factors, and 
# replacing unknown/missing/not reported as NA. 
cascadeData <- hivData %>%
  select(c(all_of(impVars), otherVars, postcode)) %>% # Drop postcode later
  mutate(sex = ifelse(sex == "unknown", NA, sex),
    cob = ifelse(cob == "Not Reported", NA, cob),
    expgroup = ifelse(expgroup == "unknown", NA, expgroup)) %>%
  mutate(diag_region = ifelse(diag_region == "Not Reported", NA, 
    diag_region)) %>% 
  mutate(diag_region = ifelse(diag_region == "Unknown", NA, 
    diag_region)) %>%
  mutate(state = as.factor(state),
    diag_region = as.factor(diag_region),
    sex = as.factor(sex), 
    cob = as.factor(cob), 
    expgroup = as.factor(expgroup)) 

# Save cascade data in impute folder
write_csv(cascadeData, file.path(setsPath, "cascadeHIVdata.csv"))

```

```{r Initial manual imputation}
# This chunk is for checking the missing and filling in any values that can
# be inferred manually

# Load packages for imputing
LoadLibrary(mice)

# Let's look at what is missing in imputeData
md.pattern(select(cascadeData, impVars))

# One NA for state which should be NSW based on diag_region
# filter(imputeData, is.na(state))  
# From 2018 no longer missing
if (dataYear < 2018) {
  cascadeData[is.na(cascadeData$state), ]$state <- "nsw"
}

# Check if any msm have missing or wrong gender - three msm are 
# designated female - replace exposure with "pwid" as coded MSM-IDU
# (confirmed to be female)

indices <- which(cascadeData$sex == "female" & cascadeData$expgroup == "msm")
cascadeData[indices, ]$expgroup <- "pwid"

# Fix up issues with postcodes -------------------------------------------
# The postcode varaible iss ssupposed to record postcode of residence at 
# the time of diagnosis. However, sometimes the place of diagnosis is
# recorded instead which can be in a different state. Here we search for 
# erroneous postcodes (based on not corresponding to the state) for each 
# state and classify them as missing. Number of erroneous postcodes: 
# ACT = 36; NSW = 50; NT = 5; QLD = 197; SA = 4; Tas = 0; Vic = 45; WA = 7. 

actPostcodes <- c(200:299, 2600:2618, 2900:2920)
actErr <- which(cascadeData$state == "act" & 
    !(cascadeData$postcode %in% actPostcodes) & 
    !is.na(cascadeData$diag_region))
# length(actErr)
# imputeData[actErr, ]
if (length(actErr) != 0) cascadeData[actErr, ]$postcode <- NA

nswPostcodes <- c(1000:2599, 2619:2899, 2921:2999, 3586, 3644, 3707)
nswErr <- which(cascadeData$state == "nsw" & 
    !(cascadeData$postcode %in% nswPostcodes) & 
    !is.na(cascadeData$diag_region))
# length(nswErr)
# imputeData[nswErr, ]
if (length(nswErr) != 0) cascadeData[nswErr, ]$postcode <- NA

ntPostcodes <- 800:999
ntErr <- which(cascadeData$state == "nt" & 
    !(cascadeData$postcode %in% ntPostcodes) & 
    !is.na(cascadeData$diag_region))
# length(ntErr)
# imputeData[ntErr, ]
if (length(ntErr) != 0) cascadeData[ntErr, ]$postcode <- NA

qldPostcodes <- c(4000:4999, 9000:9999)
qldErr <- which(cascadeData$state == "qld" & 
    !(cascadeData$postcode %in% qldPostcodes) & 
    !is.na(cascadeData$diag_region))
# length(qldErr)
# imputeData[qldErr, ]
if (length(qldErr) != 0) cascadeData[qldErr, ]$postcode <- NA

saPostcodes <- 5000:5999
saErr <- which(cascadeData$state == "sa" & 
    !(cascadeData$postcode %in% saPostcodes) & 
    !is.na(cascadeData$diag_region))
# length(saErr)
# imputeData[saErr, ]
if (length(saErr) != 0) cascadeData[saErr, ]$postcode <- NA

tasPostcodes <- 7000:7999
tasErr <- which(cascadeData$state == "tas" & 
    !(cascadeData$postcode %in% tasPostcodes) & 
    !is.na(cascadeData$diag_region))
# length(tasErr)
# imputeData[tasErr, ]
if (length(tasErr) != 0) cascadeData[tasErr, ]$postcode <- NA

vicPostcodes <- c(3000:3999, 8000:8999)
vicErr <- which(cascadeData$state == "vic" & 
    !(cascadeData$postcode %in% vicPostcodes) & 
    !is.na(cascadeData$diag_region))
# length(vicErr)
# imputeData[vicErr, ]
if (length(vicErr) != 0) cascadeData[vicErr, ]$postcode <- NA

waPostcodes <- 6000:6999
waErr <- which(cascadeData$state == "wa" & 
    !(cascadeData$postcode %in% waPostcodes) & 
    !is.na(cascadeData$diag_region))
# length(waErr)
# imputeData[waErr, ]
if (length(waErr) != 0) cascadeData[waErr, ]$postcode <- NA



```

```{r Run imputation} 
# This chunk runs the imputation on the imputeData set using the MICE 
# package. This imputation is run independently for each state to make sure
# diag_region does not mismatch with state. All imputed sets are saved for
# testing and merging later.   

# Separate data for imputing and other data - we use a little function
# to extract and modify the state data
imputeData <- cascadeData %>%
  select(impVars) # Drop postcode later
otherData <- cascadeData %>%
  select(otherVars) %>%
  rownames_to_column(var = "notification") %>%
  mutate(notification = as.integer(notification))

# Due to issues with state and diag_region not aligning following
# imputation. Run imputation separately for each state then
# combine.

# A little function to extract and modify state other data
stateData <- function(impState) {
  stateDiags <- filter(cascadeData, state == impState)
  imputeState <- stateDiags %>% select(impVars)
  otherState<- stateDiags %>%
    select(otherVars) %>%
    mutate(notification = 1:nrow(.)) %>%
    select(notification, everything())
  
  return(list(imputeState, otherState))
}

# Now produce the separate 
imputeDataACT <- stateData("act")[[1]]
otherDataACT <- stateData("act")[[2]]
imputeDataNSW <- stateData("nsw")[[1]]
otherDataNSW <- stateData("nsw")[[2]]
imputeDataNT <- stateData("nt")[[1]]
otherDataNT <- stateData("nt")[[2]]
imputeDataQLD <- stateData("qld")[[1]]
otherDataQLD <- stateData("qld")[[2]]
imputeDataSA <- stateData("sa")[[1]]
otherDataSA <- stateData("sa")[[2]]
imputeDataTAS <- stateData("tas")[[1]]
otherDataTAS <- stateData("tas")[[2]]
imputeDataVIC <- stateData("vic")[[1]]
otherDataVIC <- stateData("vic")[[2]]
imputeDataWA <- stateData("wa")[[1]]
otherDataWA <- stateData("wa")[[2]]

if (runImpute) {
  # Run imputation 
  
  # Multiple imputation using MICE
  numImputeSets <- 10
  maxIterations <- 5 # set to default
  impMethod <- "pmm"
  impSeed <- 500
  imputeSequence <- c("yeardiagnosis", "state", "agehiv", "sex",
    "expgroup", "cob", "diag_region")
  predictorMatrix <- matrix(c(0, 1, 1, 1, 1, 1, 1,
    1, 0, 1, 1, 1, 1, 1,
    1, 1, 0, 1, 1, 0, 0,
    1, 1, 1, 0, 1, 0, 0,
    1, 1, 1, 1, 0, 0, 0,
    1, 1, 1, 1, 1, 0, 1,
    1, 1, 1, 1, 1, 1, 0), byrow = TRUE, nrow = 7)
  colnames(predictorMatrix) <- imputeSequence
  rownames(predictorMatrix) <- imputeSequence
  
  
  # Run the imputation for each state
  imputeSetsACT <- mice(imputeDataACT, m = numImputeSets, 
    maxit = maxIterations, method = impMethod, seed = impSeed,
    visitSequence = imputeSequence, predictorMatrix = predictorMatrix)
  imputeSetsNSW <- mice(imputeDataNSW, m = numImputeSets, 
    maxit = maxIterations, method = impMethod, seed = impSeed,
    visitSequence = imputeSequence, predictorMatrix = predictorMatrix)
  imputeSetsNT <- mice(imputeDataNT, m = numImputeSets, 
    maxit = maxIterations, method = impMethod, seed = impSeed,
    visitSequence = imputeSequence, predictorMatrix = predictorMatrix)
  imputeSetsQLD <- mice(imputeDataQLD, m = numImputeSets, 
    maxit = maxIterations, method = impMethod, seed = impSeed,
    visitSequence = imputeSequence, predictorMatrix = predictorMatrix)
  imputeSetsSA <- mice(imputeDataSA, m = numImputeSets, 
    maxit = maxIterations, method = impMethod, seed = impSeed,
    visitSequence = imputeSequence, predictorMatrix = predictorMatrix)
  imputeSetsTAS <- mice(imputeDataTAS, m = numImputeSets, 
    maxit = maxIterations, method = impMethod, seed = impSeed,
    visitSequence = imputeSequence, predictorMatrix = predictorMatrix)
  imputeSetsVIC <- mice(imputeDataVIC, m = numImputeSets, 
    maxit = maxIterations, method = impMethod, seed = impSeed,
    visitSequence = imputeSequence, predictorMatrix = predictorMatrix)
  imputeSetsWA <- mice(imputeDataWA, m = numImputeSets, 
    maxit = maxIterations, method = impMethod, seed = impSeed,
    visitSequence = imputeSequence, predictorMatrix = predictorMatrix)
  
  # Imputed values are in the imp field stored as a matrix for each variable.
  # Each Row is the row number of the missing value and each column is the 
  # imputed value (number of columns equals the number of imputed sets).  
  
  if (saveImpute) {
    #Save imputeSets to file for loading later
    save(imputeSetsACT, imputeSetsNSW, imputeSetsNT, imputeSetsQLD,
      imputeSetsSA, imputeSetsTAS, imputeSetsVIC, imputeSetsWA,
      file = file.path(setsPath, "ImputeSets.Rda"))
  }
  
} else {
  #Load already run imputeSets 
  load(file.path(setsPath, "ImputeSets.Rda"))
}

```

```{r Complete imputation}
# Fill in all the missing values for each state then combine with other 
# data

cascadeDataImputeACT <- as_tibble(complete(imputeSetsACT, 
  action = "long")) %>%
  rename(impute_set = .imp, notification = .id) %>%
  left_join(otherDataACT, by = "notification")

cascadeDataImputeNSW <- as_tibble(complete(imputeSetsNSW, 
  action = "long")) %>%
  rename(impute_set = .imp, notification = .id) %>%
  left_join(otherDataNSW, by = "notification")

cascadeDataImputeNT <- as_tibble(complete(imputeSetsNT, 
  action = "long")) %>%
  rename(impute_set = .imp, notification = .id) %>%
  left_join(otherDataNT, by = "notification")

cascadeDataImputeQLD <- as_tibble(complete(imputeSetsQLD, 
  action = "long")) %>%
  rename(impute_set = .imp, notification = .id) %>%
  left_join(otherDataQLD, by = "notification")

cascadeDataImputeSA <- as_tibble(complete(imputeSetsSA, 
  action = "long")) %>%
  rename(impute_set = .imp, notification = .id) %>%
  left_join(otherDataSA, by = "notification")

cascadeDataImputeTAS <- as_tibble(complete(imputeSetsTAS, 
  action = "long")) %>%
  rename(impute_set = .imp, notification = .id) %>%
  left_join(otherDataTAS, by = "notification")

cascadeDataImputeVIC <- as_tibble(complete(imputeSetsVIC, 
  action = "long")) %>%
  rename(impute_set = .imp, notification = .id) %>%
  left_join(otherDataVIC, by = "notification")

cascadeDataImputeWA <- as_tibble(complete(imputeSetsWA, 
  action = "long")) %>%
  rename(impute_set = .imp, notification = .id) %>%
  left_join(otherDataWA, by = "notification")

# Merge all state sets
cascadeDataImpute <- bind_rows(cascadeDataImputeACT, cascadeDataImputeNSW,
  cascadeDataImputeNT, cascadeDataImputeQLD, cascadeDataImputeSA,
  cascadeDataImputeTAS, cascadeDataImputeVIC, cascadeDataImputeWA)
cascadeDataImpute <- cascadeDataImpute %>%
  mutate(notification = 1:nrow(.))

```

```{r Check imputation}
if (runChecks) {
  # This chunk produces a number of plots and tables to assess the 
  # imputation The primary purpose is to make sure the imputation values 
  # align proportionally with the known values
  
  impVars # For reference
  
  # yeardiagnosis is complete and state is complete following manual fix. 
  # The other variables have missing data. We create a function here so we 
  # can look at each state separately. 
  
  imputeCheck <- function(imputeSet, dataSet, completeSet, file = NULL) {
    # Nested function to check imputation for each state
    
    # diag_region - this is a variable with substantial amount of missing
    # data. Here we calculate the proportions and see the average overall 
    # number for each diagnosis region for comparison. Likely to be a lot  
    # of uncertainty especially with small numbers.
    
    # Set-up data frame - note levels contain all regions across Australia
    # so have to filter later
    diagProp <- tibble(diag_region = levels(completeSet$diag_region))
    
    for (ii in 1:10) {
      # If no imputations done then just replace with data
      if (nrow(imputeSet$imp$diag_region) != 0) {
        diagProp[, paste0("set", toString(ii))] <- 
          as.vector(table(imputeSet$imp$diag_region[, ii]) / 
              sum(table(imputeSet$imp$diag_region[, ii]))) # imputed
      } else {
        diagProp[, paste0("set", toString(ii))] <- 
          as.vector(table(dataSet$diag_region) / 
              sum(table(dataSet$diag_region)))
      }
    }
    
    diagProp <- diagProp %>%
      mutate(average = rowMeans(select(., -diag_region), na.rm = TRUE)) %>%
      mutate(data = as.vector(table(filter(dataSet, 
        !is.na(diag_region))$diag_region) / sum(table(filter(dataSet,
          !is.na(diag_region))$diag_region))),
        pre2000data = as.vector(table(filter(filter(dataSet, !is.na(diag_region)),
          yeardiagnosis <= 2000)$diag_region) / 
          sum(table(filter(filter(dataSet, !is.na(diag_region)), 
            yeardiagnosis <= 2000)$diag_region))),
        overall = as.vector(table(completeSet$diag_region) / 
          sum(table(completeSet$diag_region)))) %>%
      mutate(ave_number =  as.vector(table(completeSet$diag_region) / 10)) %>%
      filter(diag_region %in% as.character(unique(completeSet$diag_region)))
    
    # sex
    sexProp <- tibble(sex = levels(completeSet$sex))
    
    for (ii in 1:10) {
      # If no imputations done then just replace with data
      if (nrow(imputeSet$imp$sex) != 0) {
        sexProp[, paste0("set", toString(ii))] <- 
          as.vector(table(imputeSet$imp$sex[, ii]) / 
              sum(table(imputeSet$imp$sex[, ii]))) # imputed
      } else {
        sexProp[, paste0("set", toString(ii))] <- 
          as.vector(table(dataSet$sex) / 
              sum(table(dataSet$sex)))
      }
    }
    
    sexProp <- sexProp %>%
      mutate(average = rowMeans(select(., -sex), na.rm = TRUE)) %>%
      mutate(data = as.vector(table(filter(dataSet, !is.na(sex))$sex) / 
          sum(table(filter(dataSet, !is.na(sex))$sex))),
        pre2000data = as.vector(table(filter(filter(dataSet, !is.na(sex)), 
          yeardiagnosis <= 2000)$sex) / 
          sum(table(filter(filter(dataSet, !is.na(sex)), 
            yeardiagnosis <= 2000)$sex))),
        overall = as.vector(table(completeSet$sex) / 
          sum(table(completeSet$sex))))
    
    # cob - this is a variable with substantial amount of missing data
    # Here we calculate the proportions and see the average overall number
    # for each country of birth for comparison. Likely to be a lot of 
    # uncertainty especially with small numbers.
    # 
    # Set-up data frame - note levels contain all countries across 
    # Australia so have to filter later
    cobProp <- tibble(cob = levels(completeSet$cob))
    
    for (ii in 1:10) {
      # If no imputations done then just replace with data
      if (nrow(imputeSet$imp$cob) != 0) {
        cobProp[, paste0("set", toString(ii))] <- 
          as.vector(table(imputeSet$imp$cob[, ii]) / 
              sum(table(imputeSet$imp$cob[, ii]))) # imputed
      } else {
        cobProp[, paste0("set", toString(ii))] <- 
          as.vector(table(dataSet$cob) / 
              sum(table(dataSet$cob)))
      }
    }
    
    cobProp <- cobProp %>%
      mutate(average = rowMeans(select(., -cob), na.rm = TRUE)) %>%
      mutate(data = as.vector(table(filter(dataSet, !is.na(cob))$cob) / 
          sum(table(filter(dataSet, !is.na(cob))$cob))),
        pre2000data = as.vector(table(filter(filter(dataSet, !is.na(cob)), 
            yeardiagnosis <= 2000)$cob) / 
          sum(table(filter(filter(dataSet, !is.na(cob)), 
            yeardiagnosis <= 2000)$cob))),
        overall = as.vector(table(completeSet$cob) / 
          sum(table(completeSet$cob)))) %>%
      mutate(ave_number =  as.vector(table(completeSet$cob) / 10)) %>%
      filter(cob %in% as.character(unique(completeSet$cob)))
    
    # agehiv - calculate mean age of diagnosis. We do a density plot
    # later outsied the function
    meanAge <- tibble(agehiv = "meanAge")
    
    for (ii in 1:10) {
      # If no imputations done then just replace with data
      if (nrow(imputeSet$imp$agehiv) != 0) {
        meanAge[, paste0("set", toString(ii))] <- 
          mean(imputeSet$imp$agehiv[, ii]) # imputed
      } else {
        meanAge[, paste0("set", toString(ii))] <- 
          mean(dataSet$agehiv) # imputed  
      }
    }
    
    meanAge <- meanAge %>%
      mutate(average = rowMeans(select(., -agehiv), na.rm = TRUE)) %>%
      mutate(data = mean(dataSet$agehiv, na.rm = TRUE),
        pre2000data = mean(filter(dataSet, yeardiagnosis <= 2000)$agehiv,
          na.rm = TRUE),
        overall = mean(completeSet$agehiv))
    
    # expgroup 
    expProp <- tibble(expgroup = levels(completeSet$expgroup))
    
    for (ii in 1:10) {
      # If no imputations done then just replace with data
      if (nrow(imputeSet$imp$expgroup) != 0) {
        expProp[, paste0("set", toString(ii))] <- 
          as.vector(table(imputeSet$imp$expgroup[, ii]) / 
              sum(table(imputeSet$imp$expgroup[, ii]))) # imputed
      } else {
        meanAge[, paste0("set", toString(ii))] <- 
          as.vector(table(dataSet$expgroup) / 
              sum(table(dataSet$expgroup)))
      }
    }
    
    expProp <- expProp %>%
      mutate(average = rowMeans(select(., -expgroup), na.rm = TRUE)) %>%
      mutate(data = as.vector(table(filter(dataSet, !is.na(expgroup))$expgroup) / 
          sum(table(filter(dataSet, !is.na(expgroup))$expgroup))),
        pre2000data = as.vector(table(filter(filter(dataSet, !is.na(expgroup)), 
            yeardiagnosis <= 2000)$expgroup) / 
          sum(table(filter(filter(dataSet, !is.na(expgroup)), 
            yeardiagnosis <= 2000)$expgroup))),
        overall = as.vector(table(completeSet$expgroup) / 
          sum(table(completeSet$expgroup))))
    
    # Save tables to csv files if file is specified
    if (!is.null(file)) {
      write_csv(diagProp, paste0(file, "_diagProp.csv"))
      write_csv(sexProp, paste0(file, "_sexProp.csv"))
      write_csv(cobProp, paste0(file, "_cobProp.csv"))
      write_csv(meanAge, paste0(file, "_meanAge.csv"))
      write_csv(expProp, paste0(file, "_expProp.csv")) 
    }
    
    #Return outputs in a list
    output <- list("diag_region" = diagProp, "sex" = sexProp, 
      "cob" = cobProp, "age" = meanAge, "exp" = expProp)
  }  
  
  # Check for each state to investigate
  fileBase <- file.path(setsPath, "impute_checks") 
  dir.create(fileBase, showWarnings = FALSE, recursive = TRUE)
  
  actCheck <- imputeCheck(imputeSetsACT, imputeDataACT, 
    cascadeDataImputeACT, file = file.path(fileBase, "ACT"))
  nswCheck <- imputeCheck(imputeSetsNSW, imputeDataNSW, 
    cascadeDataImputeNSW, file = file.path(fileBase, "NSW"))
  ntCheck <- imputeCheck(imputeSetsNT, imputeDataNT, 
    cascadeDataImputeNT, file = file.path(fileBase, "NT"))
  qldCheck <- imputeCheck(imputeSetsQLD, imputeDataQLD, 
    cascadeDataImputeQLD, file = file.path(fileBase, "QLD"))
  saCheck <- imputeCheck(imputeSetsSA, imputeDataSA, 
    cascadeDataImputeSA, file = file.path(fileBase, "SA"))
  tasCheck <- imputeCheck(imputeSetsTAS, imputeDataTAS, 
    cascadeDataImputeTAS, file = file.path(fileBase, "TAS"))
  vicCheck <- imputeCheck(imputeSetsVIC, imputeDataVIC, 
    cascadeDataImputeVIC, file = file.path(fileBase, "VIC"))
  waCheck <- imputeCheck(imputeSetsWA, imputeDataWA, 
    cascadeDataImputeWA, file = file.path(fileBase, "WA"))
  
  # agehiv - Density plots ------------------------------------------------
  densityplot(imputeSetsACT, ~agehiv) # Warning - only 2 missing ages
  densityplot(imputeSetsNSW, ~agehiv) # 83 missing ages
  # densityplot(imputeSetsNT, ~agehiv) # No missing ages
  # densityplot(imputeSetsQLD, ~agehiv) # No missing ages
  densityplot(imputeSetsSA, ~agehiv) # Warning - only 2 missing ages
  # densityplot(imputeSetsTAS, ~agehiv) # No missing ages
  densityplot(imputeSetsVIC, ~agehiv) # 103 missing ages
  # densityplot(imputeSetsWA, ~agehiv) # No missing ages
  
  # Check for mismatches between sex and exposure -------------------------
  for (ii in 1:numImputeSets) {
    temp <- filter(cascadeDataImpute, impute_set == ii, 
      sex == "female", expgroup == "msm")
    print(nrow(temp))
  }
}

if (changeFemaleMsm) {
  # Seems to be around 5 to 30 mismatches in each set. Should be okay to 
  # change all msm to male. 
  indices <- which(cascadeDataImpute$sex == "female" & 
      cascadeDataImpute$expgroup == "msm")
  if (length(indices) != 0) {
    cascadeDataImpute[indices, ]$sex <- "male"
  }
}

```

```{r Update and save final set}
# Save final set of imputed notifications as a large data frame
write_csv(cascadeDataImpute, file.path(setsPath, 
  "cascadeHIVimputed.csv"))

```

