HIV Treatment and Suppression
=============================

Neil Arvin Bretana and Richard T. Gray

For this script to work the following data files are required or need 
updating:
- pharmdash_HIVpatientsYEAR.csv
- ~/project_care_cascades/data/ABS_population_sizes_PharmDash.xlsx

```{r initialization}
# Chunk to setup everything

# Open as a project (setting working directory to source and restarting R) 

# Setup directories
basePath <- file.path(dirname(getwd()), "HIV")
Rcode <- file.path(dirname(getwd()), "code") 
dataFolder <- file.path(basePath, "data")
outputFolder <- file.path(basePath, "output")
HIVcode <- file.path(basePath, "code") 

# Load standard libraries and options ----------------------------------
source(file.path(Rcode, "LoadLibrary.R"), echo=TRUE)
# source(file.path(Rcode, "DataLibraries.R"), echo=TRUE)
source(file.path(Rcode, "PlotOptions.R"), echo=TRUE)
LoadLibrary(tidyverse)
LoadLibrary(readxl)

# Primary script parameters
analysisYear <- 2021
replaceValues <- TRUE
saveResults <- TRUE

fitYear <- 2019 # ART Estimates analysis year 2014, 2017, or 2019 for 
# replacing 2011-2013 values

addTempRes <- TRUE # Add estimates for temporary residents on ART
usePercent <- TRUE # To add temporary residents for subpopulations

```

```{r Functions}
source(file.path(HIVcode, "pharmDashError.R"), echo=TRUE)
source(file.path(HIVcode, "ReplaceEstimates.R"), echo=TRUE)

```

```{r Treatment}
# Calculate the number taking ART during the year. This uses a mixture of 
# data sets as the Prospection data is only available for 2013-2014. For 
# the  national overall estimates we use previously generated estimates
# produced by the script 0-ArtAnalysis.Rmd. 

# Note values are all data estimates except for the year 2011:2012 for the 
# national data which is replaced by a fitted value. Load up to 
# 2000-fitYear ART estimates to get the estimates

# String tag
if (addTempRes) {
  trString <- "PBS-Ineligible"
} else {
  trString <- "PBS"
}

artEstimates <- read.csv(file.path(outputFolder, 
  paste0("ART_Estimates-", fitYear, "-", trString, ".csv")))

if (analysisYear < 2020) {
  pbsFile <- file.path(dataFolder, paste0("pharmdash_HIVpatients_clean-",
    analysisYear, ".csv"))
} else {
  pbsFile <- file.path(dataFolder, paste0("pbs_art_clean-",
    analysisYear, ".csv"))
  pbsFile_lower <- file.path(dataFolder, paste0("pbs_art-lower_clean-",
    analysisYear, ".csv"))
}

# Load PBS data to get gender and state estimates
pbsData <- read_csv(pbsFile) 

# Tidy up the prospection data
hivTreatedPbs <- pbsData %>%
  filter(gender == "all") %>%
  select(-gender) %>%
  as_tibble() 

# Append overall gender data 
genderTreatedPbs <- pbsData %>%
  filter(gender %in% c("m", "f"), state == "all") %>%
  select(-state) %>%
  mutate(gender = ifelse(gender == "m", "male", "female")) %>%
  as_tibble()

yearNames <- strsplit(toString(2013:analysisYear), ", ")[[1]]

colnames(hivTreatedPbs) <- c("population", yearNames)
hivTreatedPbs <- gather(hivTreatedPbs,"year", "value",
  2:ncol(hivTreatedPbs))
hivTreatedPbs$year <- as.numeric(as.character(hivTreatedPbs$year))

colnames(genderTreatedPbs) <- c("population", yearNames)

genderTreatedPbs <- gather(genderTreatedPbs,"year", "value",
  2:ncol(genderTreatedPbs))
genderTreatedPbs$year <- as.numeric(as.character(genderTreatedPbs$year))

hivTreatedPbs <- bind_rows(hivTreatedPbs, genderTreatedPbs)

if (analysisYear >= 2020) {
  # Need to do lower estimates as well
  pbsDataLower <- read_csv(pbsFile_lower) #, as.is = c(1, 2))
  
  hivTreatedPbsLower <- pbsDataLower %>%
  filter(gender == "all") %>%
  select(-gender) %>%
  as_tibble()
  
  # Append overall gender data 
  genderTreatedPbsLower <- pbsDataLower %>%
    filter(gender %in% c("m", "f"), state == "all") %>%
    select(-state) %>%
    mutate(gender = ifelse(gender == "m", "male", "female")) %>%
    as_tibble()
  
  colnames(hivTreatedPbsLower) <- c("population", yearNames)
  hivTreatedPbsLower <- gather(hivTreatedPbsLower,"year", "value",
    2:ncol(hivTreatedPbsLower))
  hivTreatedPbsLower$year <- as.numeric(as.character(hivTreatedPbsLower$year))
  
  colnames(genderTreatedPbsLower) <- c("population", yearNames)
  
  genderTreatedPbsLower <- gather(genderTreatedPbsLower,"year", "value",
    2:ncol(genderTreatedPbsLower))
  genderTreatedPbsLower$year <- as.numeric(as.character(genderTreatedPbsLower$year))
  
  hivTreatedLower <- bind_rows(hivTreatedPbsLower, genderTreatedPbsLower)
  
}

# Set-up range columns
hivTreatedPbs$lower <- NA
hivTreatedPbs$upper <- NA

# Sort out artEstimates
artEstimates <- artEstimates %>%
  select(year, alladjust, fitmin, fitmax, rel, rellower, relupper) %>%
  rename(value = alladjust, lower = fitmin, upper = fitmax, 
    trend = rel, trendlwr = rellower, trendupr = relupper) %>%
  mutate(population = "all") %>%
  select(population, everything())

# Bind all our ART data together
uncertainYear <- 2012
hivTreated <- rbind(filter(select(artEstimates, -contains("trend")), 
  year <= uncertainYear), # AHOD data to 2012, Prospection data 2013 for all
  filter(hivTreatedPbs, population == "all", year > uncertainYear),
  # All other populations since end of 2012
  filter(hivTreatedPbs, population != "all", year > uncertainYear))

# Add stage column
hivTreated$stage <- "numART"

# Calculate number on treatment for states and genders -------------------

# Use the relative rates to number in states

populations <- c("nsw", "vic", "qld", "nt",  "wa",  "sa",  "tas", "act", 
  "male", "female")

# Estimate state values for 2000-2012 using artEstimate trends (up to 
# 2014)

for (pop in populations) {
  
  # index positions
  # index2013 <- nrow(filter(artEstimates, year <= 2013))
  # indexFinal <- index2013 + 1
  
  # Extract final year data 
  treatFinal <- filter(hivTreated, population == pop) #,
  # year %in% c(2013:analysisYear))
  
  # Calculate estimates and ranges
  tempFit <- tail(treatFinal$value, 1) * 
    artEstimates$trend #[1:indexFinal] 
  # tempFit[index2013:indexFinal] <- treatFinal$value
  tempLwr <- tempFit * artEstimates$trendlwr #[1:indexFinal]
  tempUpr <- tempFit * artEstimates$trendupr #[1:indexFinal]
  
  # Create a data frame 
  tempDf <- tibble(population = pop, year = 2000:fitYear,
    value = tempFit, lower = tempLwr, upper = tempUpr, 
    stage = "numART")
  
  # Append data prior to 2013 
  hivTreated <- rbind(hivTreated, filter(tempDf, year <= uncertainYear))
}

# Order by state and year
hivTreated <- hivTreated %>%
  arrange(population, year) %>%
  filter(year <= analysisYear)

if (analysisYear < 2020) {
  # Calculate uncertainty in Prospection data 
  if (analysisYear < 2019) { 
    popData <- read_excel(file.path(dirname(dirname(dataFolder)), "data",
      "ABS_population_sizes_PharmDash.xlsx"),
      sheet = 2)
  } else {
    
    popData <- read_csv(file.path(dirname(dirname(dataFolder)), "data",
      paste0("ABS_population_sizes_PharmDash-", analysisYear, ".csv")))
  }
  
  # Loop through years and regions appending lower and upper
  prospectionYears <- 2013:analysisYear #2013:2019
  regions <- c(populations, "all")
  
  for (nyear in prospectionYears) {
    for (pop in regions) {
      numArt <- filter(hivTreated, year == nyear, population == pop)$value
      numPop <- filter(popData, year == nyear, population == pop)$erp
      
      error <- PharmDashError(numPop, numArt)
      
      hivTreated[(hivTreated$year == nyear & 
          hivTreated$population == pop) , ]$lower <- error$lower
      hivTreated[(hivTreated$year == nyear & 
          hivTreated$population == pop) , ]$upper <- error$upper
      
    } 
  }
} else {
  # Add lower and upper bounds - prospection data for 2013 and directly 
  # afterwards.  
  
  popData <- read_csv(file.path(dirname(dirname(dataFolder)), "data",
      paste0("ABS_population_sizes_PharmDash-", analysisYear, ".csv")))
  
  prospectionYears <- 2013
  regions <- c(populations, "all")
  
  for (nyear in prospectionYears) {
    for (pop in regions) {
      numArt <- filter(hivTreated, year == nyear, population == pop)$value
      numPop <- filter(popData, year == nyear, population == pop)$erp
      
      error <- PharmDashError(numPop, numArt)
      
      hivTreated[(hivTreated$year == nyear & 
          hivTreated$population == pop) , ]$lower <- error$lower
      hivTreated[(hivTreated$year == nyear & 
          hivTreated$population == pop) , ]$upper <- error$upper
      
    } 
  }
  
  pbsYears <- 2014:analysisYear
  
  for (pop in regions) {
    
    hivTreated[(hivTreated$year %in% pbsYears & hivTreated$population == pop),
      ]$lower <- filter(hivTreatedLower, year %in% pbsYears, population == pop)$value
    
    hivTreated[(hivTreated$year %in% pbsYears & hivTreated$population == pop),
      ]$upper <- filter(hivTreated, year %in% pbsYears, population == pop)$value
  }
}

# Add medicare ineligibles
if (addTempRes) {
  # Load from file ATRAS estimates merged with NAPHWA estimates in March 
  # 2019 report.
  tempResData <- read.csv(file.path(dataFolder,
    paste0("ART_medicare_ineligible-", analysisYear, ".csv")))
  
  tempResArt <- filter(tempResData, year <= analysisYear)
  
  if (usePercent) {
    # Use percentage Medicare ineligible to inflate past treatment
    # estimates for > 2013 (AHOD estimates already include temporary 
    # residents)
    
    endTempRes <- tail(tempResArt$value, 1)  
    endTempResMin <- tail(tempResArt$lower, 1)
    endTempResMax <- tail(tempResArt$upper, 1)
    
    endAll <- tail(filter(hivTreated, population == "all")$value, 1)
    endLower <- tail(filter(hivTreated, population == "all")$lower, 1)
    endUpper <- tail(filter(hivTreated, population == "all")$upper, 1)
    
    tempResPropAll <- endTempRes/(endTempRes + endAll)
    tempResPropMin <- endTempResMin/(endTempResMin + endLower)
    tempResPropMax <- endTempResMax/(endTempResMax + endUpper)
    
    # Gender
    atrasMale <- 133/180
    atrasFemale <- 47/180
    
    # States
    
    # Do adjustments for all subpopulations
    pops <- c("act", "all", "female", "male", "nsw", "nt", "qld", "sa", 
      "tas", "vic", "wa")
    # treatFactor <- c(1, 1, atrasFemale, atrasMale, 1, 1, 1, 1, 1, 1, 1)
    
    pbsIndices <- 14:(analysisYear - 2000 + 1) #2013:analysisYear
    for (ii in 1:length(pops)) {
      tempTreated <- filter(hivTreated, population == pops[ii])
      
      tempEnd <- tail(tempTreated$value, 1)
      tempEndLower <- tail(tempTreated$lower, 1)
      tempEndUpper <- tail(tempTreated$upper, 1)
      
      if (pops[ii] == "female") {
        tempRes <- atrasFemale * endTempRes
        tempResMin <- atrasFemale * endTempResMin
        tempResMax <- atrasFemale * endTempResMax
      } else if (pops[ii] == "male") {
        tempRes <- atrasMale * endTempRes
        tempResMin <- atrasMale * endTempResMin
        tempResMax <- atrasMale * endTempResMax
      } else {
        tempRes <- endTempRes * tempEnd / endAll
        tempResMin <- endTempResMin * tempEndLower / endLower
        tempResMax <- endTempResMax * tempEndUpper / endUpper
      }
      
      tempProp <- tempRes/(tempRes + tempEnd)
      tempPropMin <- tempResMin/(tempResMin + tempEnd)
      tempPropMax <- tempResMax/(tempResMax + tempEnd)
      
      
      hivTreated$value[hivTreated$population == pops[ii]][pbsIndices] <- 
        tempTreated$value[pbsIndices] /(1-tempProp)
      hivTreated$lower[hivTreated$population == pops[ii]][pbsIndices] <- 
        tempTreated$lower[pbsIndices] /(1-tempPropMin)
      hivTreated$upper[hivTreated$population == pops[ii]][pbsIndices] <- 
        tempTreated$upper[pbsIndices] /(1-tempPropMax)
    }
    
  } else {
    
    # Replace with updated values
    
    for (ii in 1:nrow(tempResArt)) {
      hivTreated <- hivTreated %>%
        mutate(value = ifelse(population == tempResArt$population[ii] &
            year == tempResArt$year[ii] &
            stage == "numART", 
          value + tempResArt$value[ii],
          value),
          lower = ifelse(population == tempResArt$population[ii] &
              year == tempResArt$year[ii] &
              stage == "numART", 
            lower + tempResArt$lower[ii],
            lower),
          upper = ifelse(population == tempResArt$population[ii] &
              year == tempResArt$year[ii] &
              stage == "numART", 
            upper + tempResArt$upper[ii],
            upper))
    }
  }
}

# Replace values with hard coded if necessary
# hardCodeValues <- read.csv(file.path(dataFolder,
#                                      "Hard_coded_estimates.csv"))
if (replaceValues) {
  hardCodeValues <- read.csv(file.path(dataFolder,
    "Hard_coded_estimates.csv"), as.is = 1:3)
  tempHardCode <- filter(hardCodeValues, stage == "numART")
  if (nrow(tempHardCode) > 0) {
    hivTreated <- ReplaceEstimates(hivTreated, tempHardCode)
  }
}

```

```{r suppressed}
# Calculate the number on ART with suppressed virus during the year. This uses 
# data from AHOD data and the number of people receiving treatment. 

# Initialize final results data frame
hivSuppressed <- data.frame(stage = character(), 
  year = double(),
  population = character(),
  value = double(),
  lower = double(),
  upper = double())

# Load all the data we need
ahodData <- read_csv(file.path(dataFolder, 
  paste0("ahod", analysisYear, ".csv"))) 

# Extract the viral suppression data


if (analysisYear < 2019) {
  propSuppressedState <- ahodData %>%
    select(one_of(c("year", "state", "population", "n_id")), 
      starts_with("n_rx"), -n_rx) %>% 
    filter(population == "all") %>%
    group_by(year, state) %>%
    summarise(n = sum(n_id),
      n200 = sum(n_rx200)) %>%
    mutate(prop200 = n200/n) %>%
    # Added 95% confidence interval
    mutate(prop200lower = prop200 - qnorm(0.975) * 
        sqrt(prop200 * (1 - prop200) / n),
      prop200upper = prop200 + qnorm(0.975) * 
        sqrt(prop200 * (1 - prop200) / n)) %>%
    mutate(prop200lower = ifelse(prop200lower < 0, 0, prop200lower),
      prop200upper = ifelse(prop200upper < 0, 0, prop200upper)) %>%
    filter(year <= analysisYear) %>%
    ungroup() %>%
    rename(population = state)
  
  # Append male and female data
  propSuppressedGender <- ahodData %>%
    select(one_of(c("year", "state", "population", "n_id")), 
      starts_with("n_rx"), -n_rx) %>% 
    filter(population %in% c("male", "female"), state == "all") %>%
    mutate(population = tolower(population)) %>%
    select(-state) %>%
    group_by(year, population) %>%
    summarise(n = sum(n_id),
      n200 = sum(n_rx200)) %>%
    mutate(prop200 = n200/n) %>%
    # Added 95% confidence interval
    mutate(prop200lower = prop200 - qnorm(0.975) * 
        sqrt(prop200 * (1 - prop200) / n),
      prop200upper = prop200 + qnorm(0.975) * 
        sqrt(prop200 * (1 - prop200) / n)) %>%
    mutate(prop200lower = ifelse(prop200lower < 0, 0, prop200lower),
      prop200upper = ifelse(prop200upper < 0, 0, prop200upper)) %>%
    filter(year <= analysisYear) %>%
    ungroup()
} else {
  # num_viro added to reflect viral load testing
  propSuppressedState <- ahodData %>%
    select(one_of(c("year", "state", "population", "num_viro")), 
      starts_with("n_rx"), -n_rx) %>% 
    filter(population == "all") %>%
    group_by(year, state) %>%
    summarise(n = sum(num_viro),
      n200 = sum(n_rx200)) %>%
    mutate(prop200 = n200/n) %>%
    # Added 95% confidence interval
    mutate(prop200lower = prop200 - qnorm(0.975) * 
        sqrt(prop200 * (1 - prop200) / n),
      prop200upper = prop200 + qnorm(0.975) * 
        sqrt(prop200 * (1 - prop200) / n)) %>%
    mutate(prop200lower = ifelse(prop200lower < 0, 0, prop200lower),
      prop200upper = ifelse(prop200upper < 0, 0, prop200upper)) %>%
    filter(year <= analysisYear) %>%
    ungroup() %>%
    rename(population = state)
  
  # Append male and female data
  propSuppressedGender <- ahodData %>%
    select(one_of(c("year", "state", "population", "num_viro")), 
      starts_with("n_rx"), -n_rx) %>% 
    filter(population %in% c("male", "female"), state == "all") %>%
    mutate(population = tolower(population)) %>%
    select(-state) %>%
    group_by(year, population) %>%
    summarise(n = sum(num_viro),
      n200 = sum(n_rx200)) %>%
    mutate(prop200 = n200/n) %>%
    # Added 95% confidence interval
    mutate(prop200lower = prop200 - qnorm(0.975) * 
        sqrt(prop200 * (1 - prop200) / n),
      prop200upper = prop200 + qnorm(0.975) * 
        sqrt(prop200 * (1 - prop200) / n)) %>%
    mutate(prop200lower = ifelse(prop200lower < 0, 0, prop200lower),
      prop200upper = ifelse(prop200upper < 0, 0, prop200upper)) %>%
    filter(year <= analysisYear) %>%
    ungroup() 
}

propSuppressedState$population <-
  as.character(propSuppressedState$population)
propSuppressed <- rbind(as.data.frame(propSuppressedState),
  as.data.frame(propSuppressedGender))

dataStart <- min(propSuppressed$year) 

# Loop through populations and calculate number suppressed. 
populations <- c("act", "nsw", "vic", "qld", "nt", "wa", "sa", "tas",
  "all", "male", "female")
availablePops <- c("all", "nsw", "vic", "qld", "male", "female")

for (pop in populations) {
  # Proportion suppressed
  if(pop %in% availablePops) {
    tempDf <- filter(propSuppressed, population == pop)
  } else {
    tempDf <- filter(propSuppressed, population == "all")
  }
  
  tempProp <- tempDf$prop200
  tempPropMin <- tempDf$prop200lower
  tempPropMax <- tempDf$prop200upper
  
  # Number treated 
  treatDf <- filter(hivTreated, stage == "numART", 
    population == pop, year >= dataStart)
  tempTreat <- treatDf$value
  tempTreatMin <- treatDf$lower
  tempTreatMax <- treatDf$upper
  
  # nyears <- length(tempDf$year)
  
  # Number suppressed
  hivSuppressed <- rbind(hivSuppressed, 
    data.frame(stage = "suppressed",  
      year = tempDf$year,
      population = pop,
      value = tempTreat * tempProp,
      lower = tempTreatMin * tempPropMin,
      upper = tempTreatMax * tempPropMax)) 
}

# Replace values with hard coded if necessary
if (replaceValues) {
  tempHardCode <- filter(hardCodeValues, stage == "suppressed")
  if (nrow(tempHardCode) > 0) {
    hivSuppressed <- ReplaceEstimates(hivSuppressed, tempHardCode)
  }
}

```


```{r Save results}
# Save ART and suppression results dataframe
if (saveResults) {
  
  finalResults <- bind_rows(hivTreated, hivSuppressed) %>%
    select(stage, everything())
  
  # Directory and file name
  saveString <- file.path(outputFolder, 
    paste0("HIVtreatment-", toString(analysisYear), "-", trString))
  
  # Write to csv
  write.csv(finalResults, file = paste0(saveString, ".csv"), 
    row.names = FALSE)
}

```
