PLHIV and Undiagnosed
=====================

Neil Bretana and Richard T. Gray

This script calculates the number of people living with HIV in
Australia from the estimates of people living with diagnosed HIV and
the number undiganosed produced by the ECDC HIV Modelling tool. 

This notebook is currently in draft form for updating the HIV cascade 
calculation scripts to version 3.0.

```{r Initialization}
# Chunk to setup everything

# Open as a project (setting working directory to source and restarting R)

# Setup directories
basePath <- file.path(dirname(getwd()), "HIV")
Rcode <- file.path(dirname(getwd()), "code") 
HIVcode <- file.path(basePath, "code") 
dataFolder <- file.path(basePath, "data")
outputFolder <- file.path(basePath, "output")

# Set working directory to source file location

# Load standard libraries and options ------------------------------------------
source(file.path(Rcode, "LoadLibrary.R"))
source(file.path(Rcode, "PlotOptions.R"))
LoadLibrary(tidyverse)
LoadLibrary(readxl)

```

```{r Script parameters}
# Chunk to enter all the script parameters we will use
analysisYear <- 2023
saveResults <- TRUE 
projectFolder <-  "ASR_2024" #"ASR_2024"
                                     # "HIV_Cascade_Paper"
cascadeFlag <- "All" # minus year
ecdcResults <- "exposure"
ecdcGroup <- "All" # Should be "All" by default but sometimes get tricky 
# file name issues.
updateECDC <- TRUE

useAdjusted <- TRUE # adjust number undiagnosed and percentage undiagnosed

# The following can only be TRUE if include and exclude ECDC have been run
addExclude <- TRUE
undiagnosedMethod <- "exclude" # "include", "exclude" (default), "average" 
undiagnosedMethod <- ifelse(cascadeFlag %in% c("Indigenous"), "include", undiagnosedMethod)
getNewInfections <- TRUE 

# Use if ECDC bootstrapping hasn't been done
doUncertainty <- TRUE # Calculate uncertainty estimates
doUncertainty <- ifelse(cascadeFlag %in% c("Indigenous", "SCAsia"), FALSE, doUncertainty)

# Produce cascadeName from the flag and analysis year. 
if (analysisYear <= 2016) {
  ecdcType <- ".xlsx"
} else {
  ecdcType <- ".xlsm"
}

cascadeName <- paste0(cascadeFlag, "-", toString(analysisYear))
ecdcChart <- paste0(ecdcGroup, "_ECDC")

```

```{r Copy ECDC output}
# This chunk copies the appropriate ECDC files to the appropriate output 
# files and renames the file.

# First check if exclude file exists and make appropriate adjustments to 
# settings
excludeFile <-  file.path(outputFolder, projectFolder, "ECDC_models",
  cascadeName, paste0(ecdcResults, "_exclude"),  "results", 
  paste0(ecdcGroup, "_Result_main.csv"))
if (!file.exists(excludeFile)) {
  addExclude <- FALSE
}
undiagnosedMethod <- ifelse(!addExclude, "include", undiagnosedMethod)
getNewInfections <- ifelse(!addExclude, FALSE, getNewInfections)

# Now sort out all the files
if (cascadeFlag == "Otherexp") {
  # Use overall undiagnosed
  ecdcFile1 <- file.path(outputFolder, projectFolder, "ECDC_models",
    paste0("All-", toString(analysisYear)), ecdcResults, "results",
    "All_Result_main.csv")
  
  ecdcFile2 <- file.path(outputFolder, projectFolder, "ECDC_models",
    paste0("All-", toString(analysisYear)), ecdcResults, "results",
    "All_Result_main_ConfIntervals.csv")
  
  ecdcFileMain <- file.path(outputFolder, projectFolder, "ECDC_models",
    paste0("All-", toString(analysisYear)), ecdcResults, "results",
    paste0("All_Charts", ecdcType))
  
  if (addExclude || getNewInfections) {
    # Copy exclude o/s results as well
    ecdcFile1Exclude <- file.path(outputFolder, projectFolder, "ECDC_models",
      paste0("All-", toString(analysisYear)), 
      paste0(ecdcResults, "_exclude"), 
      "results", "All_Result_main.csv")
    
    ecdcFile2Exclude <- file.path(outputFolder, projectFolder, "ECDC_models",
      paste0("All-", toString(analysisYear)), 
      paste0(ecdcResults, "_exclude"), "results",
      "All_Result_main_ConfIntervals.csv")
    
    ecdcFileMainExclude <- file.path(outputFolder, projectFolder, "ECDC_models",
      paste0("All-", toString(analysisYear)), 
      paste0(ecdcResults, "_exclude"), "results",
      paste0("All_Charts", ecdcType))
  }
  
} else {
  ecdcFile1 <- file.path(outputFolder, projectFolder, "ECDC_models",
    cascadeName, ecdcResults,  "results", 
    paste0(ecdcGroup, "_Result_main.csv"))
  
  ecdcFile2 <- file.path(outputFolder, projectFolder, "ECDC_models",
    cascadeName, ecdcResults,  "results", 
    paste0(ecdcGroup, "_Result_main_ConfIntervals.csv"))
  
  ecdcFileMain <- file.path(outputFolder, projectFolder, "ECDC_models",
    cascadeName, ecdcResults,  "results", 
    paste0(ecdcGroup, "_Charts", ecdcType))
  
  if (addExclude || getNewInfections) {
    # Copy exclude o/s results as well
    ecdcFile1Exclude <- file.path(outputFolder, projectFolder, "ECDC_models",
      cascadeName, paste0(ecdcResults, "_exclude"),  "results", 
      paste0(ecdcGroup, "_Result_main.csv"))
    
    ecdcFile2Exclude <- file.path(outputFolder, projectFolder, "ECDC_models",
      cascadeName, paste0(ecdcResults, "_exclude"),  "results", 
      paste0(ecdcGroup, "_Result_main_ConfIntervals.csv"))
    
    ecdcFileMainExclude <- file.path(outputFolder, projectFolder, "ECDC_models",
      cascadeName, paste0(ecdcResults, "_exclude"),  "results", 
      paste0(ecdcGroup, "_Charts", ecdcType))
  }
}

finalFile1 <- file.path(outputFolder, projectFolder, cascadeName,
  paste0(ecdcChart, ".csv"))
finalFile2 <- file.path(outputFolder, projectFolder, cascadeName,
  paste0(ecdcChart, "_confIntervals.csv"))
finalFileMain <- file.path(outputFolder, projectFolder, cascadeName,
  paste0(ecdcChart, "_Charts", ecdcType))

if (addExclude || getNewInfections) {
  finalFile1Exclude <- file.path(outputFolder, projectFolder, cascadeName,
    paste0(ecdcChart, "_exclude.csv"))
  finalFile2Exclude <- file.path(outputFolder, projectFolder, cascadeName,
    paste0(ecdcChart, "_confIntervals_exclude.csv"))
  finalFileMainExclude <- file.path(outputFolder, projectFolder, cascadeName,
    paste0(ecdcChart, "_Charts_exclude", ecdcType))
}

if (!file.exists(finalFile1) || updateECDC) {
  file.copy(ecdcFile1, finalFile1, overwrite = TRUE)
  if (file.exists(ecdcFile2)) { 
    file.copy(ecdcFile2, finalFile2, overwrite = TRUE)
  }
  file.copy(ecdcFileMain, finalFileMain, overwrite = TRUE)
  
  if (addExclude || getNewInfections) {
    file.copy(ecdcFile1Exclude, finalFile1Exclude, overwrite = TRUE)
    if (file.exists(ecdcFile2Exclude)) { 
      file.copy(ecdcFile2Exclude, finalFile2Exclude, overwrite = TRUE)
    }
    file.copy(ecdcFileMainExclude, finalFileMainExclude, overwrite = TRUE)
  }
} 

```


```{r Load data}
# Chunk to load the PLDHIV estimates and ECDC undiagnosed estimates. 

pldhiv <- read.csv(file.path(outputFolder, projectFolder, cascadeName, 
  paste0("HIVpldhivEstimates-", toString(analysisYear), ".csv"))) %>%
  filter(stage == "pldhiv")

# Read in and tidy main ECDC results file - results for best fitting curve
# Reported as the mean value in the ECDC model.

if (undiagnosedMethod == "exclude") {
  # Can just get the OS exclude ECDC file. 
  mainUndiagnosed <- read_csv(file.path(outputFolder, projectFolder, 
  cascadeName, paste0(ecdcChart, "_exclude.csv"))) %>%
  select(year, N_Alive_Diag_M, N_Und, N_Und_Alive_p) %>%
  rename(ecdc_diagnosed = N_Alive_Diag_M, undiagnosed = N_Und, 
    percent = N_Und_Alive_p)

} else {
  # Other methods need the include file
  mainUndiagnosed <- read_csv(file.path(outputFolder, projectFolder, 
  cascadeName, paste0(ecdcChart, ".csv"))) %>%
  select(year, N_Alive_Diag_M, N_Und, N_Und_Alive_p) %>%
  rename(ecdc_diagnosed = N_Alive_Diag_M, undiagnosed = N_Und, 
    percent = N_Und_Alive_p)

}


# Read in and tidy ECDC confidence interval file - the bootstrapped 
# confidence intervals are updated at the end of each run so we take 
# the lower and upper bound from the last run. 
# 
# We just take the best fit ECDC PLDHIV estimate for the adjustment
if (file.exists(file.path(outputFolder, projectFolder,
  cascadeName, paste0(ecdcChart, "_confIntervals.csv"))) & doUncertainty) {
  confIntervalUndiagnosed <- read_csv(file.path(outputFolder, projectFolder,
    cascadeName, paste0(ecdcChart, "_confIntervals.csv"))) %>%
    filter(run == max(.$run)) %>%
    select(year, N_Und_LB, N_Und_UB,
      N_Und_Alive_p_LB, N_Und_Alive_p_UB) %>%
    rename(undiagnosed_lower = N_Und_LB, 
      percent_lower = N_Und_Alive_p_LB,
      undiagnosed_upper = N_Und_UB, 
      percent_upper = N_Und_Alive_p_UB)
} else {
  confIntervalUndiagnosed <- mainUndiagnosed %>%
    mutate(undiagnosed_lower = undiagnosed,
      percent_lower = percent,
      undiagnosed_upper = undiagnosed,
      percent_upper = percent) %>%
    select(year, undiagnosed_lower, percent_lower, undiagnosed_upper,
      percent_upper)
}

undiagnosed <- left_join(mainUndiagnosed, confIntervalUndiagnosed, 
  by = "year") %>%
  select(year, ecdc_diagnosed, undiagnosed, undiagnosed_lower, undiagnosed_upper,
    percent, percent_lower, percent_upper)

# Merge undiagnosed data into one data frame
mergedData <- pldhiv %>%
  select(-stage) %>%
  rename(pldhiv = value,
    pldhiv_lower = lower,
    pldhiv_upper = upper) %>%
  left_join(., undiagnosed, by = "year") %>%
  as_tibble()

# If available and required repeat above and add exclude results
if (addExclude) {
  pldhivExclude <- read.csv(file.path(outputFolder, projectFolder, cascadeName, 
    paste0("HIVpldhivEstimates-", toString(analysisYear), "_exclude.csv"))) %>%
    filter(stage == "pldhiv")
  
  mainUndiagnosedExclude <- read_csv(file.path(outputFolder, projectFolder, 
    cascadeName, paste0(ecdcChart, "_exclude.csv"))) %>%
    select(year, N_Alive_Diag_M, N_Und, N_Und_Alive_p) %>%
    rename(ecdc_diagnosed_exclude = N_Alive_Diag_M, undiagnosed_exclude = N_Und,
      percent_exclude = N_Und_Alive_p)
  
  if (file.exists(file.path(outputFolder, projectFolder,
    cascadeName, paste0(ecdcChart, "_confIntervals_exclude.csv"))) & doUncertainty) {
    confIntervalUndiagnosedExclude <- read_csv(file.path(outputFolder, projectFolder,
      cascadeName, paste0(ecdcChart, "_confIntervals_exclude.csv"))) %>%
      filter(run == max(.$run)) %>%
      select(year, N_Und_LB, N_Und_UB,
        N_Und_Alive_p_LB, N_Und_Alive_p_UB) %>%
      rename(undiagnosed_lower_exclude = N_Und_LB, 
        percent_lower_exclude = N_Und_Alive_p_LB,
        undiagnosed_upper_exclude = N_Und_UB, 
        percent_upper_exclude = N_Und_Alive_p_UB)
  } else {
    confIntervalUndiagnosedExclude <- mainUndiagnosedExclude %>%
      mutate(undiagnosed_lower_exclude = undiagnosed_exclude,
        percent_lower_exclude = percent_exclude,
        undiagnosed_upper_exclude = undiagnosed_exclude,
        percent_upper_exclude = percent_exclude) %>%
      select(year, undiagnosed_lower_exclude, percent_lower_exclude, 
        undiagnosed_upper_exclude, percent_upper_exclude)
  }
  
  undiagnosedExclude <- left_join(mainUndiagnosedExclude, 
    confIntervalUndiagnosedExclude, by = "year") %>%
    select(year, ecdc_diagnosed_exclude, undiagnosed_exclude, 
      undiagnosed_lower_exclude, undiagnosed_upper_exclude, percent_exclude,
      percent_lower_exclude, percent_upper_exclude)
  
  # Merge undiagnosed data into one data frame
  mergedDataExclude <- pldhivExclude %>%
    select(-stage) %>%
    rename(pldhiv_exclude = value,
      pldhiv_lower_exclude = lower,
      pldhiv_upper_exclude = upper) %>%
    left_join(., undiagnosedExclude, by = "year") %>%
    as_tibble()
  
  mergedData <- left_join(mergedData, mergedDataExclude, by = "year")
  
}

if (getNewInfections) {
  # Also grab the new infections estimates - can only be done if include
  # and exclude calculations have been done
  
  # For all diagnoses
  if (undiagnosedMethod != "exclude") {
    newInfections <- read_csv(file.path(outputFolder, projectFolder, 
      cascadeName, paste0(ecdcChart, ".csv"))) %>%
      select(year, N_Inf_M) %>%
      rename(infections = N_Inf_M) %>%
      mutate(exclude = "no")
    
    if (file.exists(file.path(outputFolder, projectFolder,
      cascadeName, paste0(ecdcChart, "_confIntervals.csv"))) & doUncertainty) {
      confIntervalInfections <- read_csv(file.path(outputFolder, projectFolder, 
        cascadeName, paste0(ecdcChart, "_confIntervals.csv"))) %>%
        filter(run == max(.$run)) %>%
        select(year, N_Inf_M_LB, N_Inf_M_UB) %>%
        rename(infections_lower = N_Inf_M_LB, infections_upper = N_Inf_M_UB)
      
      newInfections <- left_join(newInfections, confIntervalInfections, 
        by = "year") %>%
        relocate(exclude, .after = last_col())
    }
  # For all diagnoses when overseas born excluded
  newInfectionsExclude <- read_csv(file.path(outputFolder, projectFolder, 
    cascadeName, paste0(ecdcChart, "_exclude.csv"))) %>%
    select(year, N_Inf_M) %>%
    rename(infections = N_Inf_M) %>%
    mutate(exclude = "yes")
  
  if (file.exists(file.path(outputFolder, projectFolder,
    cascadeName, paste0(ecdcChart, "_confIntervals.csv"))) & doUncertainty) {
    confIntervalInfectionsExclude <- read_csv(file.path(outputFolder, projectFolder, 
      cascadeName, paste0(ecdcChart, "_confIntervals_exclude.csv"))) %>%
      filter(run == max(.$run)) %>%
      select(year, N_Inf_M_LB, N_Inf_M_UB) %>%
      rename(infections_lower = N_Inf_M_LB, infections_upper = N_Inf_M_UB)
    
    newInfectionsExclude <- left_join(newInfectionsExclude,
      confIntervalInfectionsExclude, by = "year") %>%
      relocate(exclude, .after = last_col())
  }
  # Merge the two infections estimates
  newInfections <- bind_rows(newInfections, newInfectionsExclude)
  
} else {
  # For all diagnoses when overseas born excluded
  newInfectionsExclude <- read_csv(file.path(outputFolder, projectFolder, 
    cascadeName, paste0(ecdcChart, "_exclude.csv"))) %>%
    select(year, N_Inf_M) %>%
    rename(infections = N_Inf_M) %>%
    mutate(exclude = "yes")
  
  if (file.exists(file.path(outputFolder, projectFolder,
    cascadeName, paste0(ecdcChart, "_confIntervals_exclude.csv"))) & doUncertainty) {
    confIntervalInfectionsExclude <- read_csv(file.path(outputFolder, projectFolder, 
      cascadeName, paste0(ecdcChart, "_confIntervals_exclude.csv"))) %>%
      filter(run == max(.$run)) %>%
      select(year, N_Inf_M_LB, N_Inf_M_UB) %>%
      rename(infections_lower = N_Inf_M_LB, infections_upper = N_Inf_M_UB)
    
    newInfectionsExclude <- left_join(newInfectionsExclude,
      confIntervalInfectionsExclude, by = "year") %>%
      relocate(exclude, .after = last_col())
  }
  
  # Merge the two infections estimates
  newInfections <- newInfectionsExclude
  
}
}

```


```{r Undiagnosed calculations}
# This chunk produces the final calculations
# if (cascadeFlag == "Otherexp") {
#   plhiv <- mergedData %>%
#     mutate(plhiv = pldhiv/(1 - percent / 100),
#       plhiv_lower = pldhiv_lower/(1 - percent_lower / 100),
#       plhiv_upper = pldhiv_upper/(1 - percent_upper / 100)) %>%
#     select(-undiagnosed, -undiagnosed_lower, -undiagnosed_upper)
# } else {
#   plhiv <- mergedData %>%
#     mutate(pnumber = pldhiv/(1 - percent / 100) - pldhiv,
#       pnumber_lower = pldhiv_lower/(1 - percent_lower / 100) -
#         pldhiv_lower,
#       pnumber_upper = pldhiv_upper/(1 - percent_upper / 100) -
#         pldhiv_upper) %>%
#     group_by(year) %>%
#     mutate(undiag = ifelse(adjustUndiagnosed, mean(c(pnumber, undiagnosed)), pnumber),
#       undiag_lower = ifelse(adjustUndiagnosed, 
#         min(pnumber_lower, undiagnosed_lower), pnumber_lower), 
#       undiag_upper = ifelse(adjustUndiagnosed, 
#         max(pnumber_upper, undiagnosed_upper), pnumber_upper)) %>%
#     mutate(plhiv = undiag + pldhiv,
#       plhiv_lower = undiag_lower + pldhiv_lower,
#       plhiv_upper = undiag_upper + pldhiv_upper) %>%
#     mutate(undiag_percent = 100 * undiag/plhiv,
#       uplower = 100 * undiag_lower/plhiv_lower,
#       upupper = 100 * undiag_upper/plhiv_upper) 
# }

plhiv <- mergedData %>% 
  mutate(undiag_adjusted = undiagnosed * pldhiv / ecdc_diagnosed,
    undiag_adjusted_lower = undiagnosed_lower * pldhiv / ecdc_diagnosed,
    undiag_adjusted_upper = undiagnosed_upper * pldhiv / ecdc_diagnosed) %>%
  # The following should be same as percent adding for checking
  mutate(percent_adjusted = 100 * undiag_adjusted / (pldhiv + undiag_adjusted),
    percent_adjusted_lower = 100 * undiag_adjusted_lower / 
      (pldhiv_upper + undiag_adjusted_upper),
    percent_adjusted_upper = 100 * undiag_adjusted_upper / 
      (pldhiv_lower + undiag_adjusted_lower)) 

if (addExclude) {
  plhiv <- plhiv %>%
    mutate(undiag_adjusted_exclude = undiagnosed_exclude *
        pldhiv_exclude/ecdc_diagnosed_exclude,
      undiag_adjusted_lower_exclude = undiagnosed_lower_exclude *
        pldhiv_exclude/ecdc_diagnosed_exclude,
      undiag_adjusted_upper_exclude = undiagnosed_upper_exclude *
        pldhiv_exclude/ecdc_diagnosed_exclude) %>%
    # Compared to pldhiv 
    mutate(percent_adjusted_exclude = 100 * undiag_adjusted_exclude / 
        (pldhiv + undiag_adjusted_exclude),
      percent_adjusted_lower_exclude = 100 * undiag_adjusted_lower_exclude / 
        (pldhiv_upper + undiag_adjusted_upper_exclude),
      percent_adjusted_upper_exclude = 100 * undiag_adjusted_upper_exclude / 
        (pldhiv_lower + undiag_adjusted_lower_exclude))
}

# Add final number undiagnosed used for calculations
if (useAdjusted) {
  if (undiagnosedMethod == "include") {
    plhiv <- plhiv %>% 
      mutate(final_undiagnosed = undiag_adjusted,
        final_undiagnosed_lower = undiag_adjusted_lower,
        final_undiagnosed_upper = undiag_adjusted_upper)
  } else if (undiagnosedMethod == "exclude") {
    plhiv <- plhiv %>% 
      mutate(final_undiagnosed = undiag_adjusted_exclude,
        final_undiagnosed_lower = undiag_adjusted_lower_exclude,
        final_undiagnosed_upper = undiag_adjusted_upper_exclude)
  } else {
    # Average 
    plhiv <- plhiv %>% 
      mutate(final_undiagnosed = (undiag_adjusted + undiag_adjusted_exclude) / 2,
        final_undiagnosed_lower = (undiag_adjusted_lower +
            undiag_adjusted_lower_exclude) / 2,
        final_undiagnosed_upper = (undiag_adjusted_upper + 
            undiag_adjusted_upper_exclude) / 2)
  }
} else {
  if (undiagnosedMethod == "include") {
    plhiv <- plhiv %>% 
      mutate(final_undiagnosed = undiagnosed,
        final_undiagnosed_lower = undiagnosed_lower,
        final_undiagnosed_upper = undiagnosed_upper)
  } else if (undiagnosedMethod == "exclude") {
    plhiv <- plhiv %>% 
      mutate(final_undiagnosed = undiagnosed_exclude,
        final_undiagnosed_lower = undiagnosed_lower_exclude,
        final_undiagnosed_upper = undiagnosed_upper_exclude)
  } else {
    # Average 
    plhiv <- plhiv %>% 
      mutate(final_undiagnosed = (undiagnosed + undiagnosed_exclude) / 2,
        final_undiagnosed_lower = (undiagnosed_lower + undiagnosed_lower_exclude) / 2,
        final_undiagnosed_upper = (undiagnosed_upper + undiagnosed_upper_exclude) / 2)
  }
}

# Add final results 
plhiv <- plhiv %>%
  mutate(plhiv = pldhiv + final_undiagnosed,
    plhiv_lower = pldhiv_lower + final_undiagnosed_lower,
    plhiv_upper = pldhiv_upper + final_undiagnosed_upper) %>%
  mutate(undiag_percent = 100 * final_undiagnosed / plhiv,
    undiag_percent_lower = 100 * final_undiagnosed_lower / plhiv_upper,
    undiag_percent_upper = 100 * final_undiagnosed_upper / plhiv_lower) %>%
  mutate(adjusted = ifelse(useAdjusted, "yes", "no"),
    method = undiagnosedMethod)

# Extract cascade results
plhivResults <- plhiv %>% 
  mutate(stage = "infected") %>%
  select(stage, year, plhiv, plhiv_lower, plhiv_upper) %>%
  rename(value = plhiv,
    lower = plhiv_lower,
    upper = plhiv_upper)

# Save results
if (saveResults) {
  # Save cascade estimates
  saveStringPlhiv <- file.path(outputFolder, projectFolder, cascadeName, 
    paste0("HIVpositiveEstimates-", toString(analysisYear)))
  
  # Write to csv
  write_csv(plhivResults, paste0(saveStringPlhiv, ".csv")) 
  
  # Save plhiv
  saveStringUndiagnosed <- file.path(outputFolder, projectFolder, 
    cascadeName, paste0("plhivEstimates-", toString(analysisYear)))
  
  # Write to csv
  write_csv(plhiv, paste0(saveStringUndiagnosed, ".csv"))
  
  if (getNewInfections) {
    # Save new infections
    saveStringInfections <- file.path(outputFolder, projectFolder, 
      cascadeName, paste0("newInfectionsEstimates-", toString(analysisYear)))
    
    # Write to csv
    write_csv(newInfections, paste0(saveStringInfections, ".csv"))
  }
}

```
