---
title: "HIV Cascade Trends Exploration"
author: "Richard T. Gray and Neil Bretana"
date: Latest version - `r format(Sys.Date(), format="%B %d %Y")`
output: html_notebook
---

This document is used to explore trends in the Australian HIV Diagnosis 
and Care Cascade. 

```{r knitr_options, include=FALSE} 
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      include = FALSE) 
```

```{r setup}
# Clear workspace
rm(list=ls()) 
options(scipen=999)  # To get rid of scientific notation

# Setup directories
basePath <- getwd() #dirname(getwd())
Rcode <- file.path(dirname(getwd()), "code")
HIVcode <- file.path(basePath, "code") 
dataFolder <- file.path(basePath, "data")
resultsFolder <- file.path(basePath, "output")

# Set working directory to current directory
#setwd(basePath)

# Load standard libraries and options ----------------------------------
source(file.path(Rcode, "LoadLibrary.R"), echo=TRUE)
source(file.path(Rcode, "DataLibraries.R"), echo=TRUE)
source(file.path(Rcode, "PlotOptions.R"), echo=TRUE)
LoadLibrary(cowplot) # Note this masks ggsave with save_plot
LoadLibrary(captioner)
LoadLibrary(stringr)

# Function to tidy notifications
source(file.path(HIVcode, "TidyNotifications.R"), echo=TRUE)

# Script parameters
resultsYear <- 2016  # year of cascade we will plot
minYear <- 13        # how long ago do we plot things
startYear <- resultsYear - minYear + 1 
savePlots <- TRUE

# Plot specs
stages <- c("infected", "pldhiv",  
            "retained", "numART", "suppressed")
stageNames <- c("Living with HIV", "Diagnosed", 
                  "Retained in care", "Receiving ART", "Suppressed virus")
stageNamesNeat <- c("Living \n with HIV", "Diagnosed", 
                      "Retained \n in care", 
                      "Receiving \n ART", "Suppressed \n virus")

if (savePlots) {
  saveFormat <- ".png"
  # Create output directory
  figFolder <- file.path(basePath, "output", "figures",
                         toString(resultsYear))
  dir.create(figFolder, showWarnings = FALSE, recursive = TRUE)
}

```


```{r loadresults}

# Load hiv cascade dataframe
inputFile <- file.path(resultsFolder, paste("HIVcascadeEstimates-", 
  toString(resultsYear), ".csv", sep = ""))
hivCascade <- read.csv(inputFile)

# Exclude linked and retained in care
hivCascade <- filter(hivCascade, stage != "linked", stage != "retained")

# Only look at the overall national cascade
resultsAll <- filter(hivCascade,
                     population == "all",
                     year >= startYear)

# Load cleaned notifications data and tidy up for trend calculations
origHivData <- read.csv(file.path(dataFolder,
    paste0("hivnotifications", toString(resultsYear), ".csv"))) 
countryCodes <- read.csv(file.path(dataFolder, 
    "countryRegionCodes.csv"))
hivSet <- TidyNotifications(origHivData, resultsYear, countryCodes)

```


```{r simple trends}
# This chunk is used to do some simple trend analysis of the cascade
# estimates over 2006-2015. More advanced trend analyses were completed by
# Hamish McMannus but we decided a simple poisson progression of the best 
# estimates would be sufficient. Hamish's analysis is available in the 
# trend_analysis folder.

# Notifications ----------------------------------------------------------

# Notifications excluding people previouly diagnosed overseas
diagsData <- hivSet %>%
  filter(is.na(previ_diag_overseas)) %>%
  group_by(yeardiagnosis) %>%
  summarise(diags = n()) %>%
  rename(year = yeardiagnosis) %>%
  filter(year >= startYear) %>%
  mutate(overseas = "no")

trendDiags <- glm(diags ~ year, data = diagsData, family = "poisson")
coeff <- coef(trendDiags)[2]
p_value <- summary(trendDiags)$coefficients["year", "Pr(>|z|)"]
interval <- confint(trendDiags, "year", type = "Wald")

diagsPlot <- ggplot(data = diagsData, aes(x = year, y = diags)) +
  geom_line(color = asrcols[2]) + 
  geom_point(color = asrcols[2]) +
  geom_line(aes(y = predict(trendDiags, type = "response")), 
            colour = "black") +
  coord_cartesian(ylim = c(0, 1500)) +
  expand_limits(y = 0) +
  scale_y_continuous(labels = comma) +
  ylab("Annual notifications") + xlab("Year") +
  plotOpts +
      geom_text(x = 2010, y = 200, label = paste("Pseudo-R^2:",
        toString(round(rsq(trendDiags, type = "kl"), digits = 4))), 
        size = 3)

if (savePlots) {
  # Save the diagnoses plot
  ggsave(file.path(figFolder, paste0("HIVcascade-Diagnoses-",
                                     "_",
                                     toString(startYear), "-",
                                     toString(resultsYear),
                                     saveFormat)),
         plot = diagsPlot, width = 7.5, height = 6, units = "cm")
}

# Diagnostics-------------------------------------------------------------
# Aimed to produce a number of diagnostics of the poisson fit. Ended up 
# sticking with a plot and pseudo R^2 calculation. The pseudo-R^2 using 
# the rsq package https://cran.r-project.org/web/packages/rsq/index.html
# based on the calculation in the paper: Cameron & Windmeijer, An 
# R-squared measure of goodness of fit for some common nonlinear 
# regression model, Journal of Econometrics, 77 (1997) 329-342. 
# 
# Considered test for heteroscedasticity in the residuals using the 
# Breusch-Pagan test (P > 0.05 means it is okay) using bptest() from the 
# lmtest package https://cran.r-project.org/web/packages/rsq/index.html 
#  (don't think  it is valid for Poisson models).
#  Also the standard in built Chi-squared test isn't valid for Poisson
#   based on this blog post: http://thestatsgeek.com/2014/04/26/deviance-goodness-of-fit-test-for-poisson-regression/
#   Some dropped these tests and just stuck with the pseudo-R^2. 

LoadLibrary(rsq) # load the rsq package for pseudo-R^2 calculation
pseudoR2 <- rsq(trendDiags, type = "kl")

# Trends in between steps ------------------------------------------------
diffsData <- data.frame(year = diagsData$year)
diffsData$undiagnosed <- filter(resultsAll, stage == "infected")$value - 
  filter(resultsAll, stage == "pldhiv")$value
diffsData$noART <- filter(resultsAll, stage == "pldhiv")$value - 
  filter(resultsAll, stage == "numART")$value
diffsData$unsuppressed <- filter(resultsAll, stage == "numART")$value - 
  filter(resultsAll, stage == "suppressed")$value

diffSteps <- names(diffsData)[-1]

diffsData <- gather(diffsData, "stage", "value", 2:4)

diffsData$lower <- NA
diffsData$upper <- NA

trendData <- bind_rows(dplyr::select(resultsAll, year, stage, value,
                                     lower, upper), diffsData)

# HIV cascade trends ----------------------------------------------------
steps <- c(stages[stages != "retained"], diffSteps)
trendCascade <- data_frame(stage = character(8), 
                           coeff = numeric(8),
                           pvalue = numeric(8),
                           lower = numeric(8),
                           upper = numeric(8),
                           pseudoR2 = numeric(8))

# Set up to save all the models and plots
trendModels <- list()
trendPlots <- list()

for (ii in 1:7) {
  tempData <- filter(trendData, stage == steps[ii])                      
  temp <- glm(round(value) ~ year, data = tempData, family = "poisson")
  
  trendCascade$stage[ii] <- steps[ii]
  trendCascade$coeff[ii] <- coef(temp)[2]
  trendCascade$pvalue[ii] <- summary(temp)$coefficients["year",
                                                        "Pr(>|z|)"]
  tempInterval <- confint(temp, "year", type = "Wald")
  trendCascade$lower[ii] <- tempInterval[1]
  trendCascade$upper[ii] <- tempInterval[2]
  trendCascade$pseudoR2[ii] <- rsq(temp, type = "kl")
  
  trendModels[[steps[ii]]] <- temp
}

# Add diagnoses
trendCascade$stage[8] <- "diagnoses"
trendCascade$coeff[8] <- coeff
trendCascade$pvalue[8] <- p_value
trendCascade$lower[8] <- interval[1]
trendCascade$upper[8] <- interval[2]
trendCascade$pseudoR2[8] <- pseudoR2

trendModels[["diagnoses"]] <- trendDiags

# Store plots ------------------------------------------------------------
PlotTrend <- function(data, models, indicator) {
  model <- models[[indicator]]
  tempData <- filter(data, stage == indicator)
  ggplot(data = data.frame(year = tempData$year),                                  aes(x = year)) +
    geom_point(aes(y = tempData$value), colour = "black") +
    geom_line(aes(y = predict(model, type = "response")),
              colour = "red") +
    scale_x_discrete(breaks = tempData$year,
                     limits =  tempData$year) +
    ylab(paste0("Number of ", tempData$stage[1])) +
    expand_limits(y = 0) +
    plotOpts 
}

trendPlots <- lapply(steps, PlotTrend, data = trendData, 
                     models = trendModels)
names(trendPlots) <- steps

trendPlots[["diagnoses"]] <- diagsPlot

# Predictions for plotting -----------------------------------------------
PredictTrend <- function(models, indicator){
  model <- models[[indicator]]
  return(predict(model, type = "response"))
}

# write_csv(trendCascade, file.path(figFolder, paste0("Trends_cascade_", 
#         toString(startYear), "-", toString(resultsYear), ".csv")))

# Trend plots ------------------------------------------------------------
# Create a second set of time trend plots with the 
# predicted fit and pseudo-R^2. 

# Only do certain stages
plotStages <- steps

# Set base plotting data
plotData <- trendData

yLabels <- c("infected" = "Number of PLHIV",
             "pldhiv" = "Number diagnosed",
             "numART" = "Number on ART",
             "suppressed" = "Number suppressed\n(VL < 200 copies/ml)",
             "undiagnosed" = "Number undiagnosed",
             "noART" = "Number diagnosed\n not on ART",
             "unsuppressed" = 
               "Number unsuppressed\n(VL >= 200 copies/ml)")

# Loop across stages and save plots 
plotsTrend <- list()
for (ii in plotStages) {
  # Need to use local to prevent scope issues with predicted values
  local({
    ii <- ii
    #Select data we want
    tempData <- filter(trendData, stage == ii)
    
    # Add trend line and pseudo-R^2
    plotsTrend[[ii]] <<- ggplot(data = tempData, aes(x = year, 
                                                     y = value)) + 
      geom_ribbon(aes(ymin = lower, ymax = upper), 
                  fill = asrcols[2], alpha = 0.4) +
      geom_line(color = asrcols[2]) + 
      geom_point(color = asrcols[2]) +
      geom_line(aes(y = PredictTrend(trendModels, ii)), 
                colour = "black") +
      scale_x_continuous(breaks = seq(startYear,                        
                                      resultsYear, by = 3)) +
      expand_limits(y = 0) +
      scale_y_continuous(labels = comma) + 
      ylab(yLabels[ii]) + xlab("Year") +  
      plotOpts +
      geom_text(x = 2010, y = 200, label = paste("Pseudo-R^2:",
        toString(round(filter(trendCascade,
        stage == ii)$pseudoR2, digits = 4))), size = 3)
    
    # Save the current plot
    if (savePlots) {
      ggsave(file.path(figFolder, paste0("HIVcascade-Trends-", ii, "_",
                                         toString(startYear), "-",
                                         toString(resultsYear),
                                         saveFormat)),
             plot = plotsTrend[[ii]], width = 7.5, height = 6, 
             units = "cm")
    }
  }) 
}
  
# Create a group plot with trend lines
stagesTrendPlot <- plot_grid(plotsTrend[[1]], plotsTrend[[2]],
                             plotsTrend[[3]], plotsTrend[[4]],
                             labels = c("A", "B", "C", "D"), ncol = 2, 
                             nrow = 2, align = "v")

stagesDiffsPlot <- plot_grid(plotsTrend[[5]], plotsTrend[[6]],
                             plotsTrend[[7]],
                             labels = c("A", "B", "C"), ncol = 2, 
                             nrow = 2, align = "v")

# Save the current plots
if (savePlots) {
  ggsave(file.path(figFolder, paste("HIVcascade-Stages-Trends_",
                                    toString(startYear), "-",
                                    toString(resultsYear),
                                    saveFormat, sep = "")),
         plot = stagesTrendPlot, width = 18, height = 15, units = "cm")
  
  ggsave(file.path(figFolder, paste("HIVcascade-Differences-Trends_",
                                    toString(startYear), "-",
                                    toString(resultsYear),
                                    saveFormat, sep = "")),
         plot = stagesDiffsPlot, width = 18, height = 15, units = "cm")
}
```

```{r segmented trends}
# This chuck is used to explore the trend in diagnosed not on ART which 
# seems to have a change point. We use the library segmented and with 
# Poisson models 

library(segmented)

# Estimates for diagnoses not on ART
noartData <- filter(trendData, stage == "noART")

# Regenerate original model in case of scope issues
pmodel <- glm(round(value) ~ year, data = noartData, family = "poisson")

# Now run segmented to produce a segmented Poisson model. Varying the
# initial guess of teh breakpoint from 2007 to 2013 seems to produce no
# change in the fitted curev. 
segModel <- segmented(pmodel, seg.Z = ~year, 
                      psi = list(year = 2013))

# Summary: break points and slopes
# summary(segModel)
# segModel$psi
# segModelCI <- c(segModel$psi[2] - 1.96 * segModel$psi[3], 
#   segModel$psi[2] + 1.96 * segModel$psi[3])
# slope(segModel)

# Plot on top of trend plot
segModelData <- data.frame(year = noartData$year, 
                           segvalue = fitted(segModel))

noARTplot <- ggplot(data = noartData, aes(x = year, y = value)) + 
  geom_line(color = asrcols[2]) + 
  geom_point(color = asrcols[2]) +
  geom_line(aes(y = fitted(trendModels$noART)), 
            colour = "black") +
  geom_line(data = segModelData, aes(y = segvalue), 
            colour = "blue") + 
  scale_x_continuous(breaks = seq(startYear,                        
                                  resultsYear, by = 3)) +
  expand_limits(y = 0) +
  scale_y_continuous(labels = comma) + 
  ylab(yLabels["noART"]) + xlab("Year") +  
  plotOpts +
  geom_vline(xintercept = segModel$psi[2], linetype = "dashed",
             colour = "blue") + 
  geom_text(x = 2010, y = 600, label = paste("Overall pseudo-R^2:",
    toString(round(filter(trendCascade, stage == "noART")$pseudoR2, 
                   digits = 4))), size = 3) + 
  geom_text(x = 2010, y = 200, label = paste("Segmented pseudo-R^2:",
    toString(round(rsq(segModel, type = "kl"), 
                   digits = 4))), size = 3)

if (savePlots) {
  # Save the current plot
  ggsave(file.path(figFolder, paste0("HIVcascade-Trends-noART_Segment_",
                                     toString(startYear), "-",
                                     toString(resultsYear),
                                     saveFormat)),
         plot = noARTplot, width = 7.5, height = 6, units = "cm")
  
  # Update group plot
  stagesDiffsPlot2 <- plot_grid(diagsPlot, plotsTrend[[5]], noARTplot,
                             plotsTrend[[7]],
                             labels = c("A", "B", "C", "D"), ncol = 2, 
                             nrow = 2, align = "v")
  
  ggsave(file.path(figFolder,
                   paste("HIVcascade-Differences-Trends_Segment",
                                    toString(startYear), "-",
                                    toString(resultsYear),
                                    saveFormat, sep = "")),
         plot = stagesDiffsPlot2, width = 18, height = 15, units = "cm")
  
}

```


