# Script to calculate undiagnosed, YDF and CDR
# ============================================

```{r Set-up}
# Restart R and set working directory to source file location

# Load packages
require(tidyverse, quietly = TRUE)
require(scales, quietly = TRUE)

# Setup directories
basePath <- file.path(dirname(getwd()), "HIV")
outputFolder <- file.path(basePath, "output")

source(file.path(dirname(getwd()), "code", "PlotColors.R"))
source(file.path(dirname(getwd()), "code", "EveryNth.R"))
source(file.path(dirname(getwd()), "code", "PlotOptions.R"))

```

```{r Options}
projectName <- "ASR_2022"   # "ASR_2022" 
                            # "HIV_Cascade_Paper"
                                         
project <- file.path(basePath, "output", projectName)

# List for YDF paper
resultsYear <- 2021
cascadeList <- "All-2021" #(Include year) "All-2021"

# Result files and specifications
cascadeFile <- paste0("HIVcascadeEstimates-", resultsYear,".csv")
infectionsFile <- paste0("newInfectionsEstimates-", resultsYear,".csv")
undiagnosedFile <- paste0("plhivEstimates-", resultsYear, ".csv")

# Need all pldhiv files (which include previously diagnosed 
# overseas)to get range in deaths
diagnosesFile <- paste0("pldhiv-", resultsYear, "-all.csv")
diagnosesFileLower <- paste0("pldhiv-", resultsYear, "-min.csv")
diagnosesFileUpper <- paste0("pldhiv-", resultsYear, "-max.csv")

# Read in file with diagnoses excluding previously diagnosed overseas

ecdcFileInclude <- "All_ECDC.csv"
ecdcFileExclude <- "All_ECDC_exclude.csv"

startYear <- 2000

# New infections parameters -- Default is "exclude" because we consider
# people previously diagnosed overseas are aware of there status. 
infectsCalculation <- "exclude" # "include", "exclude" or "middle"

```

```{r extract results function}

IndicatorResults <- function(cascadeName) {
  # Read in associated cascade files and extract key columns
  infections <- read_csv(file.path(project, cascadeName, infectionsFile),
    show_col_types = FALSE)
  
  undiagnosed <- read_csv(file.path(project, cascadeName, undiagnosedFile),
    show_col_types = FALSE) %>%
    select(year, undiag = final_undiagnosed, 
      undiag_lower = final_undiagnosed_lower, 
      undiag_upper = final_undiagnosed_upper, 
      undiag_percent, 
      uplower = undiag_percent_lower,
      upupper = undiag_percent_upper) 
  
  # Read in PLDHIV files for deaths
  pldhivAll <- read_csv(file.path(project, cascadeName, diagnosesFile),
    col_types = cols(.default = "d"), show_col_types = FALSE) %>%
    select(year, diagnoses, deaths)
  pldhivLower <- read_csv(file.path(project, cascadeName, diagnosesFileLower),
    col_types = cols(.default = "d"), show_col_types = FALSE) %>%
    select(year, deaths)
  pldhivUpper <- read_csv(file.path(project, cascadeName, diagnosesFileUpper),
    col_types = cols(.default = "d"), show_col_types = FALSE) %>%
    select(year, deaths)
  
  plhiv <- read_csv(file.path(project, cascadeName, cascadeFile),
    show_col_types = FALSE) %>%
    filter(stage == "infected") %>%
    select(year, value, lower, upper) 
  
  # Read in adjusted diagnoses
  if (infectsCalculation == "include") {
    diagnoses <- read_csv(file.path(project, cascadeName, ecdcFileInclude),
      show_col_types = FALSE) %>% 
      select(year, diagnoses = N_HIV_D)
    
  } else if (infectsCalculation == "exclude") {
     diagnoses <- read_csv(file.path(project, cascadeName, ecdcFileExclude),
      show_col_types = FALSE) %>% 
      select(year, diagnoses = N_HIV_D)
  } else {
    # Its "middle"
     diagnosesInclude <- read_csv(file.path(project, cascadeName, ecdcFileInclude),
      show_col_types = FALSE) %>% 
      select(year, diagnoses_include = N_HIV_D)
     
     diagnosesExclude <- read_csv(file.path(project, cascadeName, ecdcFileExclude),
      show_col_types = FALSE) %>% 
      select(year, diagnoses_exclude = N_HIV_D)
     
     diagnoses <- diagnosesInclude %>%
         left_join(diagnosesExclude, by = "year") %>%
       mutate(diagnoses = (diagnoses_include + diagnoses_exclude) / 2) %>%
       select(year, diagnoses)
  }
  
  # Tidy up new infections estimates
  if (infectsCalculation == "include") {
    infectionsResults <- filter(infections, exclude == "no") %>%
       select(-exclude)
  } else if (infectsCalculation == "exclude") {
    infectionsResults <- filter(infections, exclude == "yes") %>%
       select(-exclude)
  } else {
    # Its "middle"
    infectionsInclude <- filter(infections, exclude == "no")
    infectionsExclude <- filter(infections, exclude == "yes")
   
    infectionsResults <- tibble(year = infectionsInclude$year,
      infections = (infectionsInclude$infections +
          infectionsExclude$infections)/2,
      infections_lower = infectionsExclude$infections_lower,
      infections_upper = infectionsInclude$infections_upper)
  }
  

  # For PLHIV create start year values for IPR calculation by shifting
  plhiv$start_plhiv <- c(plhiv$value[1], plhiv$value[1:(nrow(plhiv)-1)])
  plhiv$start_plhiv_lower <- c(plhiv$lower[1], plhiv$lower[1:(nrow(plhiv)-1)])
  plhiv$start_plhiv_upper <- c(plhiv$upper[1], plhiv$upper[1:(nrow(plhiv)-1)])

  plhiv <- plhiv %>%
    select(year, start_plhiv, start_plhiv_lower, start_plhiv_upper)
  
  # Tidy up deaths
  deaths <- pldhivAll %>%
    select(year, deaths) %>%
    mutate(deaths_lower = pldhivUpper$deaths, # opposite because we will be dividing
      deaths_upper = pldhivLower$deaths)
  
  # Merge results
  results <- diagnoses %>%
    left_join(undiagnosed, by = "year") %>%
    left_join(infectionsResults, by = "year") %>%
    left_join(plhiv, by = "year") %>%
    left_join(deaths, by = "year")
  
  return(results)
}

# Calculate ydf and cdr
AddResults <- function(results) {
  newResults <- results %>%
    mutate(ydf = diagnoses/(diagnoses + undiag),
      ydf_lower = diagnoses/(diagnoses + undiag_upper),
      ydf_upper = diagnoses/(diagnoses + undiag_lower),
      cdr = diagnoses/infections,
      cdr_lower = diagnoses/infections_upper,
      cdr_upper = diagnoses/infections_lower,
      ipr = infections/start_plhiv,
      ipr_lower = infections_lower/start_plhiv_upper,
      ipr_upper = infections_upper/start_plhiv_lower,
      imr = infections/deaths,
      imr_lower = infections_lower/deaths_upper,
      imr_upper = infections_upper/deaths_lower)
  
  return(newResults)
  
}

```

```{r Extract cascade results and calculate YDF and CDR}

results <- list()
for (cascade in cascadeList) {
  
  tempResults <- IndicatorResults(cascade) %>%
    AddResults() %>%
    filter(year >= startYear) %>%
    replace(is.na(.), 0) %>%
    mutate_all(function(x) ifelse(is.infinite(x), 0, x)) %>%
    mutate_all(function(x) ifelse(is.nan(x), 0, x))
  
  results[[cascade]] <- tempResults  
  
  write_csv(results[[cascade]], file.path(project, cascade,
    "cascadeIndicators.csv"))
  
}

```

```{r Plotting function}
cols <- unname(PlotColors()[c("Blue", "Red")])

plotUndiag <- function(df, title, ymax, indicator) {
  if (indicator == "infections") {
    # New infections
    plot <- ggplot(df, aes(x = year)) + 
      geom_ribbon(aes(ymin = infections_lower, ymax = infections_upper), 
        fill = cols[2], alpha = 0.2) +
      geom_line(aes(y=infections), colour = cols[2]) +
      labs(y = "New Infections", x = "Year", title = title) +
      scale_y_continuous(limits = c(0, ymax), 
        label = comma)
  } else if (indicator == "percent") {
    # Undiagnosed percentage - Values rescaled to proportions
    plot <- ggplot(df, aes(x = year)) + 
      geom_ribbon(aes(ymin = uplower/100, ymax = upupper/100), 
        fill = cols[2], alpha = 0.2) +
      geom_line(aes(y=undiag_percent/100), colour = cols[2]) +
      labs(y = "Percentage undiagnosed", x = "Year", title = title) +
      scale_y_continuous(limits = c(0, ymax), 
        label = percent)
  } else if (indicator == "ydf") {
    # YDF 
    plot <- ggplot(df, aes(x = year)) +
      geom_ribbon(aes(ymin = ydf_lower, ymax = ydf_upper), 
        fill = cols[2], alpha = 0.2) +
      geom_line(aes(y=ydf), colour = cols[2]) +
      labs(y = "Yearly diagnosed fraction (YDF)", x = "Year", title = title) +
      scale_y_continuous(limits = c(0, ymax), 
        label = comma)
  } else if (indicator == "cdr") {
    # CDR
    plot <- ggplot(df, aes(x = year)) + 
      geom_ribbon(aes(ymin = cdr_lower, ymax = cdr_upper), 
        fill = cols[2], alpha = 0.2) +
      geom_line(aes(y=cdr), colour = cols[2]) +
      labs(y = "Case detection rate", x = "Year", title = title) +
      scale_y_continuous(limits = c(0, ymax), 
        label = comma)
  } else if (indicator == "ipr") {
    # IPR 
    plot <- ggplot(df, aes(x = year)) + 
      geom_ribbon(aes(ymin = ipr_lower, ymax = ipr_upper), 
        fill = cols[2], alpha = 0.2) +
      geom_line(aes(y=ipr), colour = cols[2]) +
      labs(y = "Incidence prevalence ratio (IPR)", x = "Year", title = title) +
      scale_y_continuous(limits = c(0, ymax), 
        label = comma)
  } else if ((indicator == "imr")) {
    # IMR
    plot <- ggplot(df, aes(x = year)) + 
      geom_ribbon(aes(ymin = imr_lower, ymax = imr_upper), 
        fill = cols[2], alpha = 0.2) +
      geom_line(aes(y=imr), colour = cols[2]) +
      labs(y = "Incidence mortality ratio (IMR)", x = "Year", title = title) +
      scale_y_continuous(limits = c(0, ymax), 
        label = comma)
  } else {
    stop("Unknown Indicator") 
  }
  
  plot <- plot +
     scale_x_continuous(breaks = 2010:resultsYear,
    labels =  EveryNth(2010:resultsYear, 2, inverse = FALSE),
    limits = c(2010, resultsYear)) +
    PlotOptions() 
  
  return(plot)
}

```

```{r Produce and save all the plots}

plots <- list()
for (cascade in cascadeList) {
  
  print(cascade)
  
  # New infections
  tempPlot1 <- plotUndiag(results[[cascade]], cascade, 
    ceiling(max(results[[cascade]]$infections_upper)), "infections")
  
  # % Undiagnosed
  tempPlot2 <- plotUndiag(results[[cascade]], cascade, 
    ceiling(max(results[[cascade]]$upupper))/100, "percent")
  
  # YDF
  tempPlot3 <- plotUndiag(results[[cascade]], cascade, 
    ceiling(max(results[[cascade]]$ydf_upper))/2, "ydf")
  
  # CDR
  tempPlot4 <- plotUndiag(results[[cascade]], cascade, 
    ceiling(max(results[[cascade]]$cdr_upper)), "cdr")
  
  # IPR
  tempPlot5 <- plotUndiag(results[[cascade]], cascade, 
    max(results[[cascade]]$ipr_upper), "ipr")
  
  # IMR
  tempPlot6 <- plotUndiag(results[[cascade]], cascade, 
    max(results[[cascade]]$imr_upper), "imr")
  
  
  ggsave(file.path(project, cascade, "new_infections.png"), tempPlot1, 
    width = 10, height = 8, units = "cm")
  ggsave(file.path(project, cascade, "percent_undiagnosed.png"), tempPlot2, 
    width = 10, height = 8, units = "cm")
  ggsave(file.path(project, cascade, "ydf.png"), tempPlot3, 
    width = 10, height = 8, units = "cm")
  ggsave(file.path(project, cascade, "cdr.png"), tempPlot4, 
    width = 10, height = 8, units = "cm")
  ggsave(file.path(project, cascade, "ipr.png"), tempPlot5, 
    width = 10, height = 8, units = "cm")
  ggsave(file.path(project, cascade, "imr.png"), tempPlot6, 
    width = 10, height = 8, units = "cm")
  
}

```


