HIV Cascade Validation
======================

Richard T. Gray

This script reads in the HIV linkage data for treatment coverage and produces
a comparison plots against a population's cascade retention and treatment 
coverage. It is used to validate the cascade estimates and calibrate the 
migration adjustement factor for populations with PBS treatment data. 

```{r Setup}
# Open as a project (setting working directory to source and restarting R)

# Set up directories
basePath <- getwd()
cascadeFolder <- file.path(basePath, "output")

# Load standard libraries and options ----------------------------------
library("LeftysRpkg", quietly = TRUE)
LoadLibrary(tidyverse)
options(dplyr.summarise.inform = FALSE) 
LoadLibrary(readxl)
LoadLibrary(scales)

```

```{r User specified parameters}

linkageYear <- 2023
cascadeYear <- 2023

cascadeProject <- "ASR_2024"
cascadeName <- "All"

linkagePop <- "all"
artpop <- "all"
pbsPopulation <- TRUE

startYear <- 2015
endYear <- 2020

savePlots <- TRUE
extraPlots <- TRUE
extraPlots <- ifelse(pbsPopulation, extraPlots, FALSE)

```

```{r Read in data}

# Set-up data files

linkageDataFile <- file.path(cascadeFolder,
  paste0("HIV_Linkage_Broad_high_1-", linkageYear, ".csv"))

pldhivFile <- file.path(cascadeFolder, cascadeProject, 
  paste0(cascadeName, "-", cascadeYear), 
  paste0("HIVpldhivEstimates-", cascadeYear, ".csv"))

paramsFile <- file.path(cascadeFolder, cascadeProject, 
  paste0(cascadeName, "-", cascadeYear), "PldhivParameters.csv")

artFile <- file.path(cascadeFolder,
  paste0("HIVtreatment-", cascadeYear, "-PBS-Ineligible.csv"))

# Read in files ----------------------------------------------------------------

linkageRaw <- read_csv(linkageDataFile)

pldhivRaw <- read_csv(pldhivFile)

artRaw <- read_csv(artFile)

params <- read_csv(paramsFile)

# Clean data -------------------------------------------------------------------

data <-  linkageRaw |>
  filter(population == linkagePop, year  %in% startYear:endYear) |>
  dplyr::select(year, retained, treated) 

pldhiv <- pldhivRaw |> 
  filter(year %in% startYear:endYear, 
    stage %in% c("pldhiv", "retained")) |>
  dplyr::select(stage, year, value)

# Separate 12-month (lower) and 18-month window (treatment estimate) data
if (pbsPopulation) {
  
  art12 <- artRaw |> 
    filter(year %in% startYear:endYear, population == artpop, stage == "numART") |>
    dplyr::select(year, value = lower)
  
  art18 <- artRaw |> 
    filter(year %in% startYear:endYear, population == artpop, stage == "numART") |>
    dplyr::select(year, value)
  
} 

```

```{r Figure for none PBS populations}

if (!pbsPopulation) {
  
  dataAll <-  linkageRaw |>
  filter(population == "all", year  %in% startYear:endYear) |>
  dplyr::select(year, retained, treated) 
  
  data <- data |> mutate(all = dataAll$treated)
  
  treatedPlot <- ggplot(data = data,
    aes(x = year, y = treated)) +
    geom_line(aes(colour = "treated")) +
    geom_line(aes(y = all, colour = "all")) +
    scale_y_continuous(labels = percent) +
    scale_colour_manual(name = "Linkage ART percentage",
      values = c("blue", "red"),
      breaks = c("treated", "all"),
      labels = c("Population", "All")) +
    expand_limits(y = c(0.8, 1)) +
    xlab("Year") + ylab("Percent on ART") +
    PlotOptions() 
  
  treatedPlot
  
}

```

```{r Calculate cascade percentages}

if (pbsPopulation) {
  
  diagnosed <- pldhiv |> filter(stage == "pldhiv") |> pull(value)
  retained <- pldhiv |> filter(stage == "retained") |> pull(value)
  treated12 <- art12$value
  treated18 <- art18$value
  
  cascadeGaps <- tibble(year = startYear:endYear, 
    retained_estimate = retained / diagnosed, 
    art_estimate12 = treated12 / diagnosed,
    art_estimate18 = treated18 / diagnosed) |>
    left_join(data, by = "year") |> # merge in data
    pivot_longer(2:6) 
  
}
```

```{r Plot data and results}
if (pbsPopulation) {
  
  cascadeRetained <- cascadeGaps |>
    filter(str_detect(name, "retained"))
  cascadeTreat <- cascadeGaps |>
    filter(name %in% c("treated", "art_estimate12", "art_estimate18"))
  
  retainedPlot <- ggplot(data = cascadeRetained,
    aes(x = year, y = value, colour = name)) +
    geom_line() +
    scale_y_continuous(labels = percent) +
    scale_colour_manual(name = "",
      values = c("blue", "red"),
      breaks = c("retained", "retained_estimate"),
      labels = c("Linkage retained percentage", "Cascade estimates")) + 
    geom_pointrange(aes(x = 2013, y = 0.95, ymin = 0.914, ymax = 0.988), colour = "black") + 
    geom_pointrange(aes(x = 2019, y = 0.9624, ymin = 0.93, ymax = 0.99), colour = "black") + 
    expand_limits(y = c(0.9, 1)) +
    xlab("Year") + ylab("Percent retained") +  
    PlotOptions()
  
  retainedPlot
  
  treatedPlot <- ggplot(data = cascadeTreat,
    aes(x = year, y = value, colour = name)) +
    geom_line() +
    scale_y_continuous(labels = percent) +
    scale_colour_manual(name = "",
      values = c("blue", "red", "black"),
      breaks = c("treated", "art_estimate12", "art_estimate18"),
      limits = c("treated", "art_estimate12", "art_estimate18"),
      labels = c("Linkage ART\npercentage", "ART 12-month\nwindow", 
        "ART 18-month\nwindow")) +
    expand_limits(y = c(0.8, 1)) +
    xlab("Year") + ylab("Percent on ART") +
    PlotOptions() 
  
  treatedPlot
  
  treatedPlot2 <- treatedPlot +
    geom_text(x = 2015, y = 0.975, color = "black",
      label = paste0("Emmigration multiplier 1 = ", params$adjustmentStart),
      hjust = 0, size = 4) +
    geom_text(x = 2015, y = 0.96, color = "black",
      label = paste0("Emmigration multiplier 2 = ", params$adjustmentStop),
      hjust = 0, size = 4)
  
}
```

```{r Save plots}

# Saved plots are in the cascade folder. Only plot the broad definition
# as that is the main comparison we are after

if (savePlots) {
  
  figureFolder <- file.path(cascadeFolder, cascadeProject, 
    paste0(cascadeName, "-", cascadeYear))
  
  if (pbsPopulation) {
    SaveFigure(figureFolder, 
      paste0("Linkage_Retained_Comparison-", linkageYear, "-Data"), 
      retainedPlot, width = 12)
    
    SaveFigure(figureFolder, 
      paste0("Linkage_ART_Comparison-", linkageYear, "-Data"),
      treatedPlot, width = 12)
    
    SaveFigure(figureFolder, 
      paste0("Linkage_ART_Comparison_Adjustments-", linkageYear, "-Data"),
      treatedPlot2, width = 12)
    
  } else {
    
    SaveFigure(figureFolder, 
      paste0("Linkage_ART_Comparison-", linkageYear, "-Data"),
      treatedPlot, width = 12)
  }
}

```

```{r Extra plots}
# Optional extra results showing cascade gaps and treatment percentage from 
# 2015 to the final year for review
if (extraPlots) {
  
  # Pull out data to the final year
  diagnosedEnd <- pldhivRaw |> 
    filter(stage == "pldhiv", year >= 2015) |> 
    pull(value)
  art12End <- artRaw |> 
    filter(year >= 2015, population == artpop, stage == "numART") |> 
    pull(lower)
  art18End <- artRaw |> 
    filter(year >= 2015, population == artpop, stage == "numART") |> 
    pull(value)
  
  # Cascade values for diagnosed and treated
  cascade <- tibble(year = startYear:cascadeYear, 
    diag = diagnosedEnd,
    art12 = art12End, 
    art18 = art18End) |>
    pivot_longer(2:4)
  
  cascadePlot <- ggplot(data = cascade, aes(x = year, y = value, colour = name)) +
    geom_line() +
    scale_y_continuous(labels = comma) +
    scale_colour_manual(name = "",
      values = c("blue", "red", "black"),
      breaks = c("diag", "art12", "art18"),
      labels = c("Diagnosed", "ART 12-month\nwindow", "ART 18-month\nwindow")) + 
    xlab("Year") + ylab("Number of people ") +
    PlotOptions()
  
  cascadePlot
  
  # Proportion on ART for each window period
  artProp <- tibble(year = startYear:cascadeYear, 
    prop12 = art12End/diagnosedEnd, 
    prop18 = art18End/diagnosedEnd) |>
    pivot_longer(2:3)
  
  propPlot <- ggplot(data = artProp, aes(x = year, y = value, colour = name)) +
    geom_line() +
    expand_limits(y = c(0.8, 1)) +
    scale_y_continuous(labels = percent) +
    scale_colour_manual(name = "",
      values = c("blue", "red"),
      breaks = c("prop12", "prop18"),
      labels = c("12-month window", "18-month window")) + 
    xlab("Year") + ylab("Percent on ART") +
    PlotOptions()
  
  propPlot
  
  artProp |> pivot_wider(names_from = "name", values_from = "value")
  
  if (savePlots) {
    
    SaveFigure(figureFolder, 
      paste0("Diagnosed_ART_Estimates-", cascadeYear, "-Data"), 
      cascadePlot, width = 12)
    
    SaveFigure(figureFolder, 
      paste0("ART_Coverage_Estimates-", cascadeYear, "-Data"),
      propPlot)
    
    # Also save the ART proportions
    write_csv(artProp |> pivot_wider(names_from = "name", values_from = "value"), 
      file.path(figureFolder, paste0("ART_Coverage_Estimates-" , cascadeYear, 
        "-Data.csv")))
    
  }
  
}

```
