HIV Cascades Calculations
=========================
  
  Author: Richard T. Gray, Neil Arvin Bretana

This script describes and contains the code for producing the HIV care 
cascade estimates for Australia. It is written in dynamic format using R 
markdown v2 within Rstudio (version 0.98.1091 with R version`r 
                            substr(R.Version()$version.string,1,15)`) (see 
                                                                       <http://rmarkdown.rstudio.com>). 

```{r initialization}
# Clear workspace
rm(list=ls()) 

# Setup directories
basePath <- file.path(dirname(getwd()), "HIV")

Rcode <- file.path(dirname(getwd()), "code") 
dataFolder <- file.path(basePath, "data")
outputFolder <- file.path(basePath, "output")
HIVcode <- file.path(basePath, "code") 
figuresFolder <- file.path(basePath, "output","figures")

# Load standard libraries and options ----------------------------------
source(file.path(Rcode, "LoadLibrary.R"), echo=TRUE)
source(file.path(Rcode, "DataLibraries.R"), echo=TRUE)
source(file.path(Rcode, "PlotOptions.R"), echo=TRUE)

# Primary script parameters
currTime <- format(Sys.time(), "%y-%m-%d") # to append to files
analysisYear <- 2015
startYear <- 1990
replaceValues <- TRUE
saveNotifications <- FALSE
bindCascade = TRUE  # TRUE if we want to store all the cascade results 
excludeOS <- FALSE
excludeAborig <- FALSE
saveResults <- TRUE

targetGender <- 'all' #M or F, Null both, add code for including/excluding NA's or missings 
targetAge <- 'all' #groups 0, 1, 2, 3, 4...
targetCob <- 'all' # all=including n/a, Thailand, etc.
targetExposure <- 'all' #hetero, msm, pwid, unknown, otherexp 
targetAtsi <- 'all' # non_indigenous or indigenous # Only used if country is Australia
targetState <- 'all' # nsw, sa, nt, qld, vic, wa, act, tas 
targetLocalRegion <- 'all' #tbd
targetGlobalRegion <- 'all' #South-east Asia, Oceania, South American, etc

# Treated
addTempRes <- TRUE # Add estimates for temporary residents on ART

# Plotting
plots = FALSE

```
```{r functions}
# Function to easily extract sub-populations of interest 
source(file.path(Rcode, "Subset.R"), echo=TRUE)
# Function is replace current estimates with estimates for 
# specific populations obtained separately for a specific time period. 
# Function to easily extract sub-populations of interest 
source(file.path(Rcode, "ReplaceEstimates.R"), echo=TRUE)
# Function to tidy notifications
source(file.path(HIVcode, "TidyNotifications.R"), echo=TRUE)
# Load function to calculate number living with diagnosed HIV
source(file.path(Rcode,"LivingDiagnosed.R"), echo=TRUE)
# Source functions for filling in missing data
source(file.path(Rcode, "FillMissing.R"), echo=TRUE)
source(file.path(Rcode, "FillDataFrame.R"), echo=TRUE)
# Function for removing duplicates annually
source(file.path(HIVcode, "DeduplicationFunctions.R"), echo=TRUE)
# Function to replace estimates
source(file.path(Rcode, "ReplaceEstimates.R"), echo=TRUE)
# Function to tidy notifications
source(file.path(HIVcode, "TidyNotifications.R"), echo=TRUE)
# Functions to output ECDC model data
source(file.path(HIVcode, "EcdcCalculations.R"), echo=TRUE)
source(file.path(HIVcode, "EcdcFiles.R"), echo=TRUE)
# Function for adjustments
source(file.path(HIVcode, "GetAdjustments.R"), echo=TRUE)

```

## Estimate cumulative HIV notifications 

```{r Clean notifications}
# This chunk loads the national notifications and subsets based on the
# specified criteria in Script paramaters

# Load cleaned notifications data
origHivData <- read.csv(file.path(dataFolder, paste0("hivnotifications",
                    toString(analysisYear), ".csv"))) 

# Read in country code data
countryCodes <- read.csv(file.path(dataFolder, "countryRegionCodes.csv"))

# Tidy up notifications for calculations
hivData <- TidyNotifications(origHivData, analysisYear, countryCodes)

# Data checks-------------------------------------------------------------

# Quick check that we are not doing analysis outside of the data
if (max(hivData$yeardiagnosis) < analysisYear) {
  stop("No data specified for final year of analysis.")
}

# HIV data variables------------------------------------------------------

# Setup variables for overarching analysis                  
allYears <- min(hivData$yeardiagnosis):analysisYear # all years of data

```

```{r Subset notifications}
# Create subsetted notifications dataframe. May have to do this multiple
# times to get the extact number of specific category and those excluded
# for inter-regional movement. E.g. MSM only in NSW as excluded will have
# non-MSM and non-NSW

if (excludeOS) {
  hivData <- filter(hivData, is.na(previ_diag_overseas))
}

hivSetAll <- filter(hivData, yeardiagnosis <= analysisYear)
annDiagsOrig <- hivSetAll %>% 
  group_by(yeardiagnosis) %>%
  summarise(notifications = n()) %>%
  mutate(totalnotifications = cumsum(notifications)) %>%
  ungroup() 

# Possibly temporary as this may be generated elsewhere
overallPropUnique <- ProportionUnique(hivSetAll,
                                      annDiagsOrig$totalnotifications,
                                      allYears)
annPropUnique <- AnnualUnique(annDiagsOrig$notifications,
                              overallPropUnique) /
  annDiagsOrig$notifications

if (excludeAborig) {
  # Set indigenous aside separately to add on later if required
  hivSetIndigenous <- filter(hivSetAll, aboriggroup == 'indigenous')
  hivSetAll <- filter(hivSetAll, aboriggroup == 'non-indigenous')
}
  
hivSetReturn <- subhivset(hivSetAll, targetAge, targetGender,
                          targetExposure, targetCob, targetAtsi,
                          targetState, targetGlobalRegion)

hivSet <- hivSetReturn[[1]]
hivSetExcluded <- hivSetReturn[[2]]
hivSetUnknown <- hivSetReturn[[3]]

```

```{r Annual notifications and proportions}
# This chunk creates a dataframe of the annual notifications for the
# specified criteria.

includeDiags <- hivSet %>% 
  group_by(yeardiagnosis) %>%
  summarise(included = n()) %>%
  ungroup() %>%
  rename(year = yeardiagnosis)
includeDiags <- FillDataFrame(allYears, includeDiags)


# If excluded and unknown is empty replace with zeros
if (length(hivSetExcluded) == 0) {
  excludedDiags <- data_frame(year = allYears,
                            excluded = 0)
} else {
  excludedDiags <- hivSetExcluded %>%
    group_by(yeardiagnosis) %>% 
    summarise(excluded = n()) %>%
    rename(year = yeardiagnosis)
  
}
excludedDiags <- FillDataFrame(allYears, excludedDiags)

if (length(hivSetUnknown) == 0) {
 unknownDiags <- data_frame(year = allYears,
                            unknown = 0)
} else {
unknownDiags <- hivSetUnknown %>%
  group_by(yeardiagnosis) %>% 
  summarise(unknown = n()) %>%
  rename(year = yeardiagnosis)
}
unknownDiags <- FillDataFrame(allYears, unknownDiags)

# Adjust included and excluded annual diagnoses propotionally to replace
# unknwons
adjustDiags <- includeDiags %>% 
  left_join(excludedDiags, by = "year") %>%
  left_join(unknownDiags, by = "year") %>%
  mutate(all = included + excluded + unknown) %>%
  mutate(included = ifelse(is.na(included), 0, included),
         excluded = ifelse(is.na(excluded), 0, excluded),
         unknown = ifelse(is.na(unknown), 0, unknown)) %>%
  mutate(prop_included = included / (included + excluded),
         prop_excluded = excluded / (included + excluded)) %>%
  mutate(prop_included = ifelse(is.nan(prop_included), 0, prop_included), 
         prop_excluded = ifelse(is.nan(prop_excluded), 0, 
                                prop_excluded)) %>%
  mutate(adjusted_included = included  + unknown * prop_included,
         adjusted_excluded = excluded + unknown * prop_excluded)

hivResults <- data_frame(year = adjustDiags$year,
                         notifications = adjustDiags$adjusted_included,
                         cumnotifications =
                           cumsum(adjustDiags$adjusted_included))

```

## Number taking ART

```{r treatment}
# Calculate the number taking ART during the year. This uses a mixture of 
# data sets as the Prospection data is only available for 2013-2014. For 
# the  national overall estimates we use previously generated estimates
# produced by the script 0-ArtAnalysis.Rmd. 

# Note values are all data estimates except for the year 2012 for the 
# national data which is replaced by a fitted value

# Load up to 2000-2014 ART estimates -- we will use other data for
# >= 2013
artEstimates <- read.csv(file.path(dataFolder, "ART_Estimates-2014.csv"))

# Reload Prospection PBS data to get gender and state estimates
prospectionData <- read.csv(file.path(dataFolder, paste0("pharmdash_HIVpatients", toString(analysisYear), ".csv")), as.is = c(1, 2))

# Tidy up the prospection data
hivTreatedPbs <- prospectionData %>%
  filter(gender == "all") %>%
  select(-gender) %>%
  tbl_df()

yearNames <- strsplit(toString(2013:analysisYear), ", ")[[1]]

colnames(hivTreatedPbs) <- c("population", yearNames)
hivTreatedPbs <- gather(hivTreatedPbs,"year", "value",
                        2:ncol(hivTreatedPbs))
hivTreatedPbs$year <- as.numeric(as.character(hivTreatedPbs$year))

# Append overall gender data 
genderTreatedPbs <- prospectionData %>%
  filter(gender %in% c("m", "f"), state == "all") %>%
  select(-state) %>%
  mutate(gender = c("male", "female")) %>%
  tbl_df()

colnames(genderTreatedPbs) <- c("population", yearNames)

genderTreatedPbs <- gather(genderTreatedPbs,"year", "value",
                        2:ncol(genderTreatedPbs))
genderTreatedPbs$year <- as.numeric(as.character(genderTreatedPbs$year))

hivTreatedPbs <- bind_rows(hivTreatedPbs, genderTreatedPbs)

# Set-up range columns
hivTreatedPbs$lower <- NA
hivTreatedPbs$upper <- NA

# Sort out artEstimates
artEstimates <- artEstimates %>%
  select(year, alladjust, fitmin, fitmax, rel, rellower, relupper) %>%
  rename(value = alladjust, lower = fitmin, upper = fitmax, 
         trend = rel, trendlwr = rellower, trendupr = relupper) %>%
  mutate(population = "all") %>%
  select(population, everything())

# Bind all our ART data together
hivTreated <- rbind(filter(select(artEstimates, -contains("trend")), 
                           year <= 2012), 
                    filter(hivTreatedPbs, population == "all"),
                    filter(hivTreatedPbs, population != "all"))

# Add stage column
hivTreated$stage <- "numART"

# Calculate number on treatment for states and genders --------------------

# Use the relative rates to number in states

populations <- c("nsw", "vic", "qld", "nt",  "wa",  "sa",  "tas", "act", 
            "male", "female")

# Estimate state values for 2000-2012 using artEstimate trends (up to 2014)
for (pop in populations) {
  # Extract final year data 
  treatFinal <- filter(hivTreated, population == pop,
                       year %in% c(2013:2014))
  
  # index positions
  indexFinal <- nrow(artEstimates)
  index2013 <- nrow(filter(artEstimates, year <= 2013))
  
  # Calculate estimates and ranges
  tempFit <- treatFinal$value[nrow(treatFinal)] * artEstimates$trend
  tempFit[index2013:indexFinal] <- treatFinal$value
  tempLwr <- tempFit * artEstimates$trendlwr
  tempUpr <- tempFit * artEstimates$trendupr
  
  # Create a data frame 
  tempDf <- data_frame(population = pop, year = 2000:2014,
                       value = tempFit, lower = tempLwr, upper = tempUpr, 
                       stage = "numART")
  
  # Append data prior to 2013 
  hivTreated <- rbind(hivTreated, filter(tempDf, year <= 2012))
}

# Order by state and year
hivTreated <- hivTreated %>%
  arrange(population, year) %>%
  filter(year <= analysisYear)


# calculate uncertainty in Prospection data -------------------------------
popData <- read_excel(file.path(dirname(dirname(dataFolder)), "data",
                                "ABS_population_sizes.xlsx"),
                      sheet = 2)
source(file.path(Rcode, "pharmDashError.R"), echo=TRUE)

# Loop through years and regions appending lower and upper
prospectionYears <- c(2013, 2014, 2015)
regions <- c(populations, "all")

for (nyear in prospectionYears) {
 for (pop in regions) {
   numArt <- filter(hivTreated, year == nyear, population == pop)$value
   numPop <- filter(popData, year == nyear, population == pop)$erp
   
   error <- PharmDashError(numPop, numArt)
   
   hivTreated[(hivTreated$year == nyear & 
                 hivTreated$population == pop) , ]$lower <- error$lower
   hivTreated[(hivTreated$year == nyear & 
                 hivTreated$population == pop) , ]$upper <- error$upper
   
   } 
}

# Add medicare ineligibles
if (addTempRes) {
  
  # Load the temporary resident estimates
  tempResArt <- read.csv(file.path(dataFolder,
                                   "ART_medicare_ineligible.csv"))
  
  # Replace with updated values
  for (ii in 1:nrow(tempResArt)) {
    hivTreated <- hivTreated %>%
      mutate(value = ifelse(population == tempResArt$population[ii] &
                            year == tempResArt$year[ii] &
                            stage == "numART", 
                            value + tempResArt$value[ii],
                            value),
             lower = ifelse(population == tempResArt$population[ii] &
                            year == tempResArt$year[ii] &
                            stage == "numART", 
                            lower + tempResArt$lower[ii],
                            lower),
             upper = ifelse(population == tempResArt$population[ii] &
                            year == tempResArt$year[ii] &
                            stage == "numART", 
                            upper + tempResArt$upper[ii],
                            upper))
  }
}

# Do some plots if required -----------------------------------------------
if (plots) {
  treatPlot1 <- ggplot(data = relTreat, aes(x = year, y = fit)) + 
    geom_point(data = s100data, aes(x = year, y =  relative), 
               color = "black", size = 4) + 
    geom_line(color = "red") +
    geom_line(aes(y = lwr), color = "blue", linetype = "dashed") +
    geom_line(aes(y = upr), color = "blue", linetype = "dashed") +
    scale_x_continuous(breaks = seq(2005, analysisYear, by =2)) +
    ylim(c(0,1.5)) +  
    ylab("Relative number on treatment") + xlab("Year") + 
    ggtitle("Fitted number on ART relative to 2012 
            (based on s100 spending)") + 
    plotOpts
  
  treatPlot2 <- ggplot(data = filter(hivTreated, population == "all"), 
                       aes(x = year, y = value)) +
    geom_line(color = "red") + 
    geom_line(aes(y = lower), color = "blue", linetype = "dashed") + 
    geom_line(aes(y = upper), color = "blue", linetype = "dashed") + 
    geom_point(data = filter(hivTreated, population == "all", 
                             year >= 2013), color = "black", size = 4) +
    scale_x_continuous(breaks = seq(2005, analysisYear, by =2)) +
    ylim(0,NA) + 
    ylab("Number on treatment") + xlab("Year") + 
    ggtitle("National number on ART") + 
    plotOpts
  
  # Save to file 
  treatPlot <- grid.arrange(treatPlot1, treatPlot2, ncol = 2)
  ggsave(file.path(figuresFolder, "treatment_rate.png"),
         plot = treatPlot, width = 15, height = 5)
}

# Replace values with hard coded if necessary
hardCodeValues <- read.csv(file.path(dataFolder, "Hard_coded_estimates.csv"))
if (replaceValues) {
  hardCodeValues <- read.csv(file.path(dataFolder, "Hard_coded_estimates.csv"))
  tempHardCode <- filter(hardCodeValues, stage == "numART")
  if (nrow(tempHardCode) > 0) {
    hivTreated <- replaceEstimates(hivTreated, tempHardCode)
  }
}

```

```{r suppressed}
# Calculate the number on ART with suppressed virus during the year. This uses 
# data from AHOD data and the number of people recieving treatment. 

# Initialize final results data frame
hivSuppressed <- data.frame(stage = character(), 
                            year = double(),
                            population = character(),
                            value = double(),
                            lower = double(),
                            upper = double())

# Load all the data we need
ahodData <- read.csv(file.path(dataFolder, 
  paste0("ahod", toString(analysisYear), ".csv")))

# Extract the viral suppression data
propSuppressedState <- ahodData %>%
# filter(state == "all") %>%
  select(one_of(c("year", "state", "population", "n_id")), 
         starts_with("n_rx"), -n_rx) %>% 
  group_by(year, state) %>%
  summarise(n = sum(n_id),
            n200 = sum(n_rx200)) %>%
  mutate(prop200 = n200/n) %>%
  # Added 95% confidence interval
  mutate(prop200lower = prop200 - qnorm(0.975) * 
           sqrt(prop200 * (1 - prop200) / n),
         prop200upper = prop200 + qnorm(0.975) * 
           sqrt(prop200 * (1 - prop200) / n)) %>%
  filter(year <= analysisYear) %>%
  ungroup() %>%
  rename(population = state)

# Append male and female data
propSuppressedGender <- ahodData %>%
  select(one_of(c("year", "state", "population", "n_id")), 
         starts_with("n_rx"), -n_rx) %>% 
  filter(population %in% c("MALE", "FEMALE"), state == "all") %>%
  mutate(population = tolower(population)) %>%
  select(-state) %>%
  group_by(year, population) %>%
  summarise(n = sum(n_id),
            n200 = sum(n_rx200)) %>%
  mutate(prop200 = n200/n) %>%
  # Added 95% confidence interval
  mutate(prop200lower = prop200 - qnorm(0.975) * 
           sqrt(prop200 * (1 - prop200) / n),
         prop200upper = prop200 + qnorm(0.975) * 
           sqrt(prop200 * (1 - prop200) / n)) %>%
  filter(year <= analysisYear) 

propSuppressedState$population <- as.character(propSuppressedState$population)
propSuppressed <- rbind(as.data.frame(propSuppressedState), as.data.frame(propSuppressedGender))

dataStart <- min(propSuppressed$year) 

# TODO: by exposure mode

# Loop through populations and calculate number suppressed. 
populations <- c("act", "nsw", "vic", "qld", "nt", "wa", "sa", "tas",
                 "all", "male", "female")
availablePops <- c("all", "nsw", "vic", "qld", "male", "female")

for (pop in populations) {
  # Proportion suppressed
  if(pop %in% availablePops) {
    tempDf <- filter(propSuppressed, population == pop)
  } else {
    tempDf <- filter(propSuppressed, population == "all")
  }
  
  tempProp <- tempDf$prop200
  tempPropMin <- tempDf$prop200lower
  tempPropMax <- tempDf$prop200upper
  
  # Number treated 
  treatDf <- filter(hivTreated, stage == "numART", 
                    population == pop, year >= dataStart)
  tempTreat <- treatDf$value
  tempTreatMin <- treatDf$lower
  tempTreatMax <- treatDf$upper
  
  # nyears <- length(tempDf$year)
  
  # Number suppressed
  hivSuppressed <- rbind(hivSuppressed, 
                         data.frame(stage = "suppressed",  
                         year = tempDf$year,
                         population = pop,
                         value = tempTreat * tempProp,
                         lower = tempTreatMin * tempPropMin,
                         upper = tempTreatMax * tempPropMax)) 
}

# Replace values with hard coded if necessary
if (replaceValues) {
  tempHardCode <- filter(hardCodeValues, stage == "suppressed")
  if (nrow(tempHardCode) > 0) {
    hivSuppressed <- replaceEstimates(hivSuppressed, tempHardCode)
  }
}

```


```{r cleanup}
# Finally bind to overall results
if (bindCascade) {
  hivCascade <- rbind(hivTreated, hivSuppressed)
}

# Save HIV results dataframe
if (saveResults) {
  # Directory and file name
  saveString <- file.path(outputFolder, 
    paste("HIVtreatment-", toString(analysisYear), sep = ""))
  
  # Write to csv
  write.csv(hivCascade, file = paste(saveString, ".csv", sep =""), 
            row.names = FALSE)
}

```
