---
title: "PldhivCalculations"
output: html_notebook
author: Neil Bretana and Richard T. Gray
---

This is a draft [R Markdown](http://rmarkdown.rstudio.com) Notebook for 
calculating the number of people living with HIV in Australia. This is one of 
the key steps for producing the estimates of the Australian HIV diagnosis and 
care cascade. 

This notebook is currently in draft form for updating the HIV cascade 
calculation scripts to version 3.0

```{r Knitr options, include=FALSE} 
# This chunk may not be necessary
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      include = FALSE) 
```

```{r Initialization}
# Chunk to setup everything
# Clear workspace
rm(list=ls()) 

# Setup directories
basePath <- file.path(dirname(getwd()), "HIV")

Rcode <- file.path(dirname(getwd()), "code") 
HIVcode <- file.path(basePath, "code") 
dataFolder <- file.path(basePath, "data")
outputFolder <- file.path(basePath, "output")
figuresFolder <- file.path(basePath, "output","figures")

# Set working directory
#setwd(basePath)

# Load standard libraries and options ----------------------------------
source(file.path(Rcode, "LoadLibrary.R"), echo=TRUE)
source(file.path(Rcode, "DataLibraries.R"), echo=TRUE)
source(file.path(Rcode, "PlotOptions.R"), echo=TRUE)

# Primary script parameters
currTime <- format(Sys.time(), "%y-%m-%d") # to append to files


```

```{r Front matter}
# This chunk might not be necessary either
mainPackages <- c("dplyr", "tidyr", "ggplot2", "markdown", "cowplot", 
                  "gridExtra")
source(file.path(Rcode, "FrontMatter.R"), echo = TRUE)
fmStr <- FrontMatter(mainPackages, rstudio = "1.0.44")
cat(fmStr)

```

```{r Script parameters}
# Chunk to enter all the script parameters we will use
analysisYear <- 2015
startYear <- 1990

plots <- FALSE       # TRUE if we want to plot things
bindCascade <- TRUE  # TRUE if we want to store all the cascade results 
                     # one data frame

saveCascade <- TRUE       # save final cascade dataframe
saveNotifications <- TRUE # save cleaned notifications set
saveResults <- TRUE       # save information national annual notifications
savePldhiv <- TRUE        # save PLDHIV estimates separately

# set hivSet function parameters
targetGender <- 'all' #M or F, Null both, add code for including/excluding NA's or missings 
targetAge <- 'all' #groups 0, 1, 2, 3, 4...
targetCob <- 'non-australia' # all=including n/a, Thailand, etc.
targetExposure <- 'all'
targetAtsi <- 'all' # 0 or 1 # Only used if country is Australia
targetState <- 'all' # NSW, VIC, etc
targetLocalRegion <- 'all' #tbd
targetGlobalRegion <- 'all' #South-east Asia, Oceania, South American, etc.

```

```{r Functions}
# Load and define useful functions for analysis 
# POTENTIALLY PUT SOME FUNCTIONS INTO A SEPARATE SCRIPT FOR SOURCING

# Load function to remove duplicates
source(file.path(Rcode,"RemoveDuplicates.R"), echo=TRUE)

# Load function to calculate number living with diagnosed HIV
source(file.path(Rcode,"LivingDiagnosed.R"), echo=TRUE)

# Source function for filling in missing data
source(file.path(Rcode, "FillMissing.R"), echo=TRUE)

# Function to easily extract sub-populations of interest 
source(file.path(Rcode, "Subset.R"), echo=TRUE)

# Function for removing duplicates annually
source(file.path(Rcode, "RemoveDuplicatesAnnually.R"), echo=TRUE)

# Function to create file name for deduplicted output
source(file.path(Rcode, "Deduplicate.R"), echo=TRUE)

# Function to create file name for deduplicted output
source(file.path(Rcode, "Deduplicate.R"), echo=TRUE)

# Function to replace estimates
source(file.path(Rcode, "ReplaceEstimates.R"), echo=TRUE)


```

```{r Clean notifications}
# SHOULD PUSH ALL THIS INTO HIV CLEAN SCRIPT

# This chunk loads the national notifications and subsets based on the
# specified criteria in Script paramaters

# Load notifications
hivData <- read.csv(file.path(dataFolder, paste("hivnotifications",
                    toString(analysisYear), ".csv", sep = ""))) 

# if (replaceValues) {
#   # Replace with hard coded estimates where necessary
#   
#   # Load hard coded estimates
#   hardCodeValues <- read.csv(file.path(dataFolder,
#                                        "Hard_coded_estimates.csv"))
# }

# Setup overarching analysis                   
years <- startYear:analysisYear # Years to calculate and plot 

# Setup extra columns for analysis
hivData$yeardiagnosis <- as.numeric(substr(hivData$datediagnosis, 1, 4))
hivData$yeardeath <- as.numeric(substr(hivData$datedeath, 1, 4))

allYears <- min(hivData$yeardiagnosis):analysisYear # All years of data

#clean aboriggroup
hivData$aboriggroup <- rep(NA,nrow(hivData))

# Aboriginal group
if (analysisYear < 2015) {
  hivData$aboriggroup[hivData$cob!=1100|hivData$rob!=7] <- "othercob"
  hivData$aboriggroup[hivData$cob==0] <- NA
  hivData$aboriggroup[hivData$cob == 1100 & hivData$indigenous == "Aboriginal"] <- "indigenous"
  hivData$aboriggroup[hivData$cob == 1100 & hivData$indigenous == "Non indigenous"] <- "non-indigenous" 
} else {
  # hivData$aboriggroup[hivData$cob!=1100] <- "othercob"
  # MAY NEED TO BE CAREFUL WITH MISSING COUNTRY OF BIRTH INDIGENOUS
  # hivData$aboriggroup[hivData$cob==0 & hivData$indigenous == "Aboriginal"] <- "indigenous"
  # hivData$aboriggroup[hivData$cob==0 & hivData$indigenous != "Aboriginal"] <- "not-reported"
  hivData$aboriggroup[hivData$cob == 1100 & hivData$indigenous == "Aboriginal"] <- "indigenous"
   hivData$aboriggroup[hivData$indigenous != "Aboriginal"] <- "non-indigenous"
  hivData$aboriggroup[is.na(hivData$aboriggroup)] <- "non-indigenous"
  # hivData$aboriggroup[hivData$cob == 1100 & hivData$indigenous == "Non-Indigenous"] <- "non-indigenous" 
  # hivData$aboriggroup[hivData$cob == 1100 & is.na(hivData$indigenous)] <- "non-indigenous"
}

# transfer cob to cobCode
hivData$cobcode <- hivData$cob

# load cob and region codes
crCodes <- read.csv(file.path(dataFolder, "countryRegionCodes.csv"))

# if cob is not in crCodes/NA, change to Not Reported 
hivData$cob[!(hivData$cobcode %in% crCodes$COUNTRY_CODE)] <- "Not Reported"

# change cob from code to String
hivData$cob <- crCodes$COUNTRY_NAME[match(hivData$cobcode, crCodes$COUNTRY_CODE)]

#add region - DO LATER?
hivData$globalregion <- crCodes$REGION[match(hivData$cobcode, crCodes$COUNTRY_CODE)]

# CHANGE NA TO NOT REPORTED AS WELL (only 22 in the data set)
hivData$cob[is.na(hivData$cob)] <- "Not Reported"

# Convert some of the not reporteds to "overseas" if country of birth is missing 
# but region of birth is available.
hivData$cob <- as.character(hivData$cob)
hivData$cob[hivData$cob == "Not Reported" & !(hivData$rob %in%  c(0,7))] <-
  "Overseas"

# Quick checks that we are not doing analysis outside of the data.
if (max(hivData$yeardiagnosis) < analysisYear) {
  stop("No data specified for final year of analysis.")
}

if (min(hivData$yeardiagnosis) > startYear) {
  stop("No data specified for first year of analysis.")
}

```

```{r Subset notifications}
# Source subset function
# Create subsetted notifications dataframe
hivSetOrig <- filter(hivData, yeardiagnosis <= analysisYear)

# Set indigenous aside separately to add on later if required
hivSetIndigenous <- filter(hivSetOrig, aboriggroup == 'indigenous')
hivSetOrig <- filter(hivSetOrig, aboriggroup == 'non-indigenous')


# if (targetCob == "australia") {
#   if (targetAtsi == "atsi") {
#     hivSetOrig <- filter(hivSetOrig, aboriggroup == 'indigenous')
#   } else if (targetAtsi == "non-atsi") {
#     hivSetOrig <- filter(hivSetOrig, aboriggroup == 'non-indigenous')
#   } else {
#     # For all need to do both separately
#     hivSetOrig <- filter(hivSetOrig, aboriggroup == 'non-indigenous')
#     hivSetIndigenous <- filter(hivSetOrig, aboriggroup == 'indigenous') 
#   }
# }
  
hivSetReturn <- subhivset(hivSetOrig, targetAge, targetExposure, targetCob, targetAtsi, targetLocalRegion, targetGlobalRegion)

hivSet <- hivSetReturn[[1]]
hivSetExcluded <- hivSetReturn[[2]]
hivSetUnknown <- hivSetReturn[[3]]

##get set of AU cob and unknowns to distribute proportion
## I ACTUALLY DONT THINK WE NEED THIS - ALSO NEED TO BE CAREFUL OF 
## INDIGENOUS IN THE CALCULATIONS
# hivSetKnown <- filter(hivData, yeardiagnosis <= analysisYear)
# hivSetKnown <- subset(hivSetKnown, cob!="Not Reported")
# hivSetKnown <- subset(hivSetKnown, !is.na(cob))
# hivSetUnknown <- filter(hivData, yeardiagnosis <= analysisYear)
# hivSetUnknown <- subset(hivSetUnknown, is.na(cob) | cob=="Not Reported")

```

```{r Annual notifications}
# This chunk creates a dataframe of the annual notifications for the specified 
# criteria.
origHivSet <- hivSetOrig %>%
  group_by(yeardiagnosis) %>%
  summarise(notifications = n()) %>%
  mutate(totalnotifications  = cumsum(notifications)) %>%
  filter(yeardiagnosis <= analysisYear)



allDiags <- hivSetOrig %>%
  group_by(yeardiagnosis) %>% 
  summarise(all = n()) 
if (length(hivSetExcluded) == 0) {
  excludedDiags <- data_frame(yeardiagnosis = allDiags$yeardiagnosis,
                            excluded = 0)
} else {
  excludedDiags <- hivSetExcluded %>%
    group_by(yeardiagnosis) %>% 
    summarise(excluded = n()) 
}

if (length(hivSetUnknown) == 0) {
 unknownDiags <- data_frame(yeardiagnosis = allDiags$yeardiagnosis,
                            unknown = 0)
} else {
unknownDiags <- hivSetUnknown %>%
  group_by(yeardiagnosis) %>% 
  summarise(unknown = n())
}
            # cob_unknown = sum(is.na(cob) | cob == "Not Reported"),
            # indigenous = sum(!is.na(aboriggroup) & aboriggroup == "indigenous"),
            # overseas = sum(cob=="Overseas"))

adjustDiags <- hivSet %>% 
  group_by(yeardiagnosis) %>%
  summarise(subset = n()) %>%
  ungroup() %>%
  right_join(allDiags, by = "yeardiagnosis") %>%
  left_join(excludedDiags, by = "yeardiagnosis") %>%
  left_join(unknownDiags, by = "yeardiagnosis") %>%
  mutate(included = ifelse(is.na(subset), 0, subset),
         excluded = ifelse(is.na(excluded), 0, excluded),
         unknown = ifelse(is.na(unknown), 0, unknown)) %>%
  mutate(prop_included = included / (included + excluded),
         prop_excluded = excluded / (included + excluded)) %>%
  mutate(prop_included = ifelse(is.nan(prop_included),0, prop_included), 
         prop_excluded = ifelse(is.nan(prop_excluded),0, prop_excluded)) %>%
  mutate(adjusted_included = included  + unknown * prop_included,
         adjusted_excluded = excluded + unknown * prop_excluded)%>%
  rename(year = yeardiagnosis)

# if (targetCob != "all") {            
  # adjustDiags <- hivSet %>% 
  #   group_by(yeardiagnosis) %>% 
  #   summarise(subset = n()) %>%
  #   ungroup() %>%
  #   right_join(annualDiags, by = "yeardiagnosis") %>%
  #   mutate(subset = ifelse(is.na(subset), 0, subset),
  #          cob_known = all - indigenous - cob_unknown) %>%
  #   mutate(non_subset = cob_known - subset - overseas) %>%
  #   mutate(prop_subset = subset / cob_known,
  #          prop_non_subset = non_subset / cob_known,
  #          prop_overseas = overseas/cob_known) %>%
  #   mutate(prop_subset = ifelse(is.nan(prop_subset),0, prop_subset),
  #          prop_non_subset = ifelse(is.nan(prop_non_subset),0, prop_non_subset),
  #          prop_overseas = ifelse(is.nan(prop_overseas),0, prop_overseas)) %>%
  #   mutate(adjusted_subset = subset  + cob_unknown * prop_subset,
  #          adjusted_non_subset = non_subset + cob_unknown *    
  #            prop_non_subset,
  #          adjusted_overseas = overseas + cob_unknown * prop_overseas) %>%
  #   rename(year = yeardiagnosis)
  # 
  # # Need to adjust appropriately
  # if (targetCob == "non-australia") {
  # # Have to add the other overseas
  # subsetDiags <- adjustDiags %>% 
  #   mutate(subset = adjusted_subset + adjusted_overseas) %>%
  #   select(year, subset)
  # } else if (targetCob == "Australia") {
  #   # Have to add the indigenous
  #   subsetDiags <- adjustDiags %>%
  #   mutate(subset = adjusted_subset - adjusted_overseas) %>%
  #   select(year, subset)
  # } else {
  #   subsetDiags <- adjustDiags %>% 
  #   mutate(subset = adjusted_subset) %>%
  #   select(year, subset)
  # }
  # 
# } else {
#   subsetDiags <- hivSet %>% 
#     group_by(yeardiagnosis) %>% 
#     summarise(subset = n()) %>%
#     rename(year = yeardiagnosis)
# }

subsetDiags <- adjustDiags

# # Need to fix up with fill missing
# hivResults <- hivSet %>% 
#   group_by(yeardiagnosis) %>% 
#   summarise(notifications = n()) %>% 
#   mutate(totalnotifications  = cumsum(notifications)) %>% 
#   filter(yeardiagnosis <= analysisYear) %>%
#   rename(year = yeardiagnosis) 
# hivResults <- bind_rows(hivResults, data_frame(year = 1981, notifications = 0, 
#                                               totalnotifications = 2))

# hivResultsKnown <- hivSetKnown %>% 
#   group_by(yeardiagnosis) %>% 
#   summarise(notifications = n()) %>% 
#   mutate(totalnotifications  = cumsum(notifications)) %>% 
#   filter(yeardiagnosis <= analysisYear) 
# 
# hivResultsUnknown <- hivSetUnknown %>% 
#   group_by(yeardiagnosis) %>% 
#   summarise(notifications = n()) %>% 
#   mutate(totalnotifications  = cumsum(notifications)) %>% 
#   filter(yeardiagnosis <= analysisYear)   
# 
# 
# # Fill in missing data and years ----------------------------------------------
# fillMissing <- as.data.frame(allYears) 
# colnames(fillMissing) <- c("yeardiagnosis")
# hivResults <- merge(fillMissing, hivResults, by="yeardiagnosis", all.x=TRUE)
# hivResults[is.na(hivResults)] <- 0
# hivResultsKnown <- merge(fillMissing, hivResultsKnown, by="yeardiagnosis", all.x=TRUE)
# hivResultsKnown[is.na(hivResultsKnown)] <- 0
# hivResultsUnknown <- merge(fillMissing, hivResultsUnknown, by="yeardiagnosis", all.x=TRUE)
# hivResultsUnknown[is.na(hivResultsUnknown)] <- 0
# 
# #Get proportion of unknown 
# proportion <- as.data.frame(allYears) 
# colnames(proportion) <- c("yeardiagnosis")
# proportion$proportion <- hivResults$notifications/hivResultsKnown$notifications
# proportion$proportion[is.na(proportion$proportion)] <- 0
# hivResults$notifications <- hivResults$notifications + floor(proportion$proportion*hivResultsUnknown$notifications)
hivResults <- data_frame(year = subsetDiags$year,
                         notifications = subsetDiags$adjusted_included)
hivResults$year <- subsetDiags$year
hivResults$notifications <- subsetDiags$adjusted_included
hivResults$totalnotifications <- cumsum(hivResults$notifications)

```

```{r Load overall estimates}
# This chunk creates or loads the overall cascade estimates for proportion 
# unique, mortality, and overses migration
#Get proportion unique
# Function to estimate proportion unique

# THIS CHUCK AHOULD BE STAND ALONE AND NOT REALY ON PREVIOUS CALCULATIONS

# source(file.path(Rcode, "ProportionUnique.R"), echo=TRUE)
# hivResults$propunique <- ProportionUnique(hivSetOrig, hivResults, origHivSet)
# hivResults$uniquecases <- hivResults$totalnotifications*hivResults$propunique

#
oldResults <- read.csv(file.path(outputFolder, "HIVresults-2015.csv"))

hivResults$uniquecases <- hivResults$totalnotifications*oldResults$propunique

# Function to estimate migration rate
source(file.path(Rcode, "EstimateMigration.R"), echo=TRUE)

#Function to estimate death rate
source(file.path(Rcode, "EstimateMortality.R"), echo=TRUE)

 hivResults$osrate <- allMigrate$rate
 hivResults$oslower <- allMigrate$lower
 hivResults$osupper <- allMigrate$upper
 
 hivResults$deathslinked <- deaths
 hivResults$deathslower <- deaths_min
 hivResults$deathsupper <- deaths_max
 
 hivResults$deathrate <- oldResults$deathrate
 hivResults$drlower <- deathRate_min
 hivResults$drupper <- deathRate_max

#save hivResults
  saveString <- file.path(outputFolder, paste("HIVresults-", 
    toString(analysisYear), sep = ""))
 save(hivResults, file = paste(saveString, ".rda", sep =""))

```

```{r Adjust parameters}
# This chuck is used to create adjusted mortality and migration rates for the 
# specified criteria

load("nonIndigenous_Adjustment.Rda")


 
```

```{r Calculate PLDHIV}
# This chunk fianlly calculates the number of people living with diagnosed HIV

if (analysisYear <= 2014) {
  propStay <- 1
  propStayLower <- 1
  propStayUpper <- 1
} else {
  propStay <- 0.98
  propStayLower <- 0.96
  propStayUpper <- 1
} 
# Initialize final results data frame
hivDiagnosed <- data.frame(stage = character(), 
                           year = double(),
                           population = character(),
                           estimate = double(),
                           lower = double(),
                           upper = double())

# First calculate overall number -----------------------------------------

# Setup all our vectors - first by filling in missing cumulative diagnoses
# filledDiagnoses <- FillMissing(allYears, hivResults$yeardiagnosis, 
#                                  hivResults$uniquecases)

# cumDiagnoses <- filledDiagnoses$value
cumDiagnoses <- hivResults$uniquecases

# All death rates used for all  populations
deathRate <- oldResults$deathrate
deathRateMin <- oldResults$drlower
deathRateMax <- oldResults$drupper

# National migration rates
# migrationRate <- filter(hivMigrate, state == "all")$rate
# migrationRateMin <- filter(hivMigrate, state == "all")$lower
# migrationRateMax <- filter(hivMigrate, state == "all")$upper

migrationRate <- oldResults$osrate

# Calculate number living with diagnosed HIV and range

pldhivAll <- LivingDiagnosed((1 - nonAborigMigrationFactor * (1-propStay)) *
                               cumDiagnoses,
                             nonAborigMortalityFactor * deathRate,
                             nonAborigMigrationFactor * migrationRate)


# Use max rates for min estimate because they are removal rates 
# and vice versa
# pldhivAllMin <- LivingDiagnosed(cumDiagnoses,
#                                 deathRateMax,
#                                 migrationRateMax,
#                                 propStayLower) 
# pldhivAllMax <- LivingDiagnosed(cumDiagnoses,
#                                 deathRateMin,
#                                 migrationRateMin,
#                                 propStayUpper) 
# 
# # Store results
 nyears <- length(allYears)
 hivDiagnosed <- rbind(hivDiagnosed, 
                       data_frame(stage = "pldhiv", 
                             year = allYears, 
                             population = "all", 
                             value = pldhivAll))
#                             lower = pldhivAllMin,
#                             upper = pldhivAllMax))
# 
# 
# # Finally bind to overall results -----------------------------------------
# if (bindCascade) {
#   hivCascade <- rbind(hivCascade, hivDiagnosed)
# }
# 
# # Replace values with hard coded if necessary
# if (replaceValues) {
#   tempHardCode <- filter(hardCodeValues, stage == "pldhiv")
#   if (nrow(tempHardCode) > 0) {
#     hivCascade <- replaceEstimates(hivCascade, tempHardCode)
#   }
# }

```


