---
title: "Australian Chlamydia Cascade"
author: Richard T. Gray
output: html_notebook
editor_options: 
  chunk_output_type: console
---

This document presents estimates for the diagnosis and care cascade for 
*Chlamydia trachomatis* infection in Australia. The methods used for the 
estimates are described at the end of the document.


```{r knitr_options, include=FALSE} 
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      include = FALSE) 
```

<!--- Code for calculating the cascade --->
```{r initialization}
# Chunk to setup everything
# 
# Open as a project (setting working directory to source and restarting R)

# Set session working directory manually to source file location
# setwd(source file location)

# Details of results and outputs folders
basePath <- getwd()
Rcode <- file.path(dirname(getwd()), "code") 
docFolder <- file.path(basePath, "docs")
dataFolder <- file.path(basePath, "data")

# Source useful functions
source(file.path(Rcode, "FormatData.R"), echo = TRUE)
source(file.path(Rcode, "LoadLibrary.R"), echo = TRUE)
source(file.path(Rcode, "DataLibraries.R"), echo = TRUE)
LoadLibrary(tidyverse)

# Current time for appending to outputs
currTime <- format(Sys.time(), "%y-%m-%d") # to append to files

# Script parameters
resultsYear <- 2016 # year of cascade we will calculate and plot     
saveCascade <- TRUE                    
saveplots <- TRUE # Save plots as separate files
fileType <- ".png" # ".png" for documents 
retestRange <- TRUE # Calculate variations in retested

```

```{r Front matter}
# Some information on the packages and versions used to generate the 
# results
mainPackages <- c("readr","dplyr", "tidyr", "ggplot2")
source(file.path(Rcode, "FrontMatter.R"))
fmStr <- FrontMatter(mainPackages, rstudio = "1.0.153")
cat(fmStr)
```

```{r loadresults}
# Load hiv cascade dataframe
notificationsFile <- file.path(dataFolder,
  paste("chlamnotifications", toString(tail(resultsYear, 1)), ".csv", 
        sep = ""))

incidenceFile <- file.path(dataFolder, paste("chlamincidence",
  toString(tail(resultsYear, 1)), ".csv", sep = ""))

treatFile <- file.path(dataFolder, paste("chlamtreatment", 
  toString(tail(resultsYear, 1)), ".csv", sep = ""))

notifications <-  read.csv(notificationsFile)
incidence <- read.csv(incidenceFile)
treatment <- read.csv(treatFile) 

  
if (retestRange) {
  retestVarFile <- file.path(dataFolder, paste("chlamRetestVariation",
    toString(tail(resultsYear, 1)), ".csv", sep = ""))  
  retests <- read.csv(retestVarFile, stringsAsFactors = FALSE) %>%
    select(-diagnoses, -retested, -year) %>%
    tbl_df()
  
  # Add GP retest estimates
  retests <- filter(treatment, stage == "retested", context == "gp") %>%
    select(region, context, sex, proportion, prop_lower, 
           prop_upper) %>%
    rename(prop_retested = proportion) %>%
    mutate(period = "42-180") %>%
    arrange(region) %>%
    bind_rows(retests,.) %>%
    tbl_df()
  
  # Add estimates for other periods by using the same relative
  # proportion. WARNING: need care to ensure rows are arranged properly!
  
  # 42-120 days
  retest120prop <- filter(retests, period == "42-120", 
                      context == "shc")$prop_retested /
    filter(retests, period == "42-180", context == "shc")$prop_retested
  retest120prop[is.nan(retest120prop)] <- 0
  
  retest120lower <- filter(retests, period == "42-120", 
                      context == "shc")$prop_lower /
    filter(retests, period == "42-180", context == "shc")$prop_lower
  retest120lower[is.nan(retest120lower)] <- 0        

  retest120upper <- filter(retests, period == "42-120", 
                      context == "shc")$prop_upper /
    filter(retests, period == "42-180", context == "shc")$prop_upper
  retest120upper[is.nan(retest120upper)] <- 0
  
  retests120 <- data_frame(region = rep(c("regional", "remote", "urban"),
                                        each = 3),
                           context = "gp",
                           sex = rep(c("males", "females", "all"), 3),
                           period = "42-120",
                           prop_retested = filter(retests,
                             context == "gp")$prop_retested * 
                             retest120prop,
                           prop_lower = filter(retests,
                             context == "gp")$prop_lower * 
                             retest120lower,
                           prop_upper = filter(retests, 
                             context == "gp")$prop_upper * 
                             retest120upper)
  
  # 7-180 days
  retest7prop <- filter(retests, period == "7-180", 
                      context == "shc")$prop_retested /
    filter(retests, period == "42-180", context == "shc")$prop_retested
  retest7prop[is.nan(retest7prop)] <- 0
  
  retest7lower <- filter(retests, period == "7-180", 
                      context == "shc")$prop_lower /
    filter(retests, period == "42-180", context == "shc")$prop_lower
  retest7lower[is.nan(retest7lower)] <- 0        

  retest7upper <- filter(retests, period == "7-180", 
                      context == "shc")$prop_upper /
    filter(retests, period == "42-180", context == "shc")$prop_upper
  retest7upper[is.nan(retest7upper)] <- 0
  
  retests7 <- data_frame(region = rep(c("regional", "remote", "urban"),
                                        each = 3),
                           context = "gp",
                           sex = rep(c("males", "females", "all"), 3),
                           period = "7-180",
                           prop_retested = filter(retests,
                             context == "gp")$prop_retested * 
                             retest7prop,
                           prop_lower = filter(retests,
                             context == "gp")$prop_lower * 
                             retest7lower,
                           prop_upper = filter(retests, 
                             context == "gp")$prop_upper * 
                             retest7upper)
  
  # Put it all together
  retests <- bind_rows(retests, retests120, retests7)
}

```

```{r extractResults}
# Extract the actual results we want - resultsYear for 15-29 year olds
currentDiags <- notifications %>% 
  filter(year %in% resultsYear) %>%
  select(-male...15.yrs, -male.30.34.yrs, -male...34.yrs, -male.all, 
         -female...15.yrs, -female.30.34.yrs, -female...34.yrs,
         -female.all)

# Current incidence
currentInc <- incidence %>% 
  filter(year %in% resultsYear)

# Current treatment data
currentTreat <- treatment %>%
  select(-source, -reference)

```

```{r calculations}
nyears <- length(resultsYear)

# Initialize output data frame
chlamcascade <- data.frame(stage = character(), sex = character(),
             estimate = numeric(), lower = numeric(), 
             upper = numeric(), percentprevious = numeric())

# New infections ---------------------------------------------------------
maleInc <- rowMeans(currentInc[, 2:3])
maleIncLower <- currentInc[, 2]
maleIncUpper <- currentInc[, 3]
femaleInc <- rowMeans(currentInc[, 4:5])
femaleIncLower <- currentInc[, 4]
femaleIncUpper <- currentInc[, 5]

chlamcascade <- rbind(chlamcascade, 
                      data.frame(stage = "infections",
                                 year = rep(resultsYear, 3),
                                 sex = rep(c("male", "female", "all"), 
                                           each = length(resultsYear)),
                                 estimate = c(maleInc, femaleInc, 
                                              maleInc + femaleInc),
                                 lower = c(maleIncLower, femaleIncLower,
                                           maleIncLower + femaleIncLower), 
                                 upper = c(maleIncUpper, femaleIncUpper,
                                           maleIncUpper + femaleIncUpper),
                                 percentprevious = c(NA, NA, NA),
                                 percentpreviousLower = c(NA, NA, NA),
                                 percentpreviousUpper = c(NA, NA, NA)))

# Diagnoses --------------------------------------------------------------

maleDiags <- rowSums(currentDiags[, 2:4])
femaleDiags <- rowSums(currentDiags[, 5:7])

if (resultsYear >= 2015) {
  # Estimate uncertainty using estimates for the Victorian 
  # 15-29 year old population due to missing data in 2015-2016 (from 
  # CT notifications_YEAR_National_Estimate.xlsx)
  
  notificationsYear <- ifelse(resultsYear == 2015, 2016, resultsYear)
  
  proportionsFile <- file.path(dataFolder, paste0("CT notifications_",
    toString(notificationsYear), "_National_Estimate.xlsx"))
  
  vicProportion <- read_excel(proportionsFile, sheet = 2, skip = 23)

  years <- vicProportion$year
  
  maleVicProp <- vicProportion$male
  femaleVicProp <- vicProportion$female
  allVicProp <- vicProportion$all
  
  propData <- data.frame(year = years, males = maleVicProp, females =
                           femaleVicProp, all = allVicProp)

  # Male estimates - produce range by using relative error for 
  # 2015 from linear regression
  malePropEst <-predict(lm(males ~ year, data = propData), 
                        newdata = data.frame(year = resultsYear), 
                        interval = "conf")
  
  lowerMaleDiags <- maleDiags * (1 - malePropEst[1]) / 
    (1 - malePropEst[2])
  upperMaleDiags <- maleDiags * (1 - malePropEst[1]) / 
    (1 - malePropEst[3])
  
  # Female estimates - produce range by using relative error for 
  # 2015 from linear regression
  femalePropEst <-predict(lm(females ~ year, data = propData), 
                          newdata = data.frame(year = 2015), 
                          interval = "conf")
  
  lowerFemaleDiags <- femaleDiags * (1 - femalePropEst[1]) / 
    (1 - femalePropEst[2])
  upperFemaleDiags <- femaleDiags * (1 - femalePropEst[1]) / 
    (1 - femalePropEst[3])
  
  # All estimates for reporting
  allPropEst <-predict(lm(all ~ year, data = propData), 
                          newdata = data.frame(year = 2015), 
                          interval = "conf")
  
  
} else {
  # Assume no error in diagnoses
  lowerMaleDiags <- NA
  upperMaleDiags <- NA
  
  lowerFemaleDiags <- NA
  upperFemaleDiags <- NA
}

# Generate cascade
chlamcascade <- rbind(chlamcascade, 
                      data.frame(stage = "notifications",
                                 year = rep(resultsYear, 3),
                                 sex = rep(c("male", "female", "all"), 
                                           each = length(resultsYear)), 
                                 estimate = c(maleDiags, femaleDiags,
                                              maleDiags + femaleDiags),
                                 lower = c(lowerMaleDiags,
                                           lowerFemaleDiags,
                                           lowerMaleDiags + lowerFemaleDiags), 
                                 upper = c(upperMaleDiags,
                                           upperFemaleDiags,
                                           upperMaleDiags + upperFemaleDiags),
                                 percentprevious = 100 * 
                                   c(maleDiags / maleInc, 
                                     femaleDiags / femaleInc,
                                     (maleDiags + femaleDiags) / 
                                       (maleInc + femaleInc)),
                                 percentpreviousLower = 100 * 
                                   c(lowerMaleDiags / maleIncUpper, 
                                     lowerFemaleDiags / femaleIncUpper,
                                     (lowerMaleDiags + lowerFemaleDiags) / 
                                       (maleIncUpper + femaleIncUpper)),
                                 percentpreviousUpper = 100 * 
                                   c(upperMaleDiags / maleIncLower, 
                                     upperFemaleDiags / femaleIncLower,
                                 (upperMaleDiags + upperFemaleDiags) / 
                                       (maleIncLower + femaleIncLower))))
                      
# Weights for calculations based on notifications ------------------------
weightsDF <- filter(currentTreat, stage == "notifications")
weights <- weightsDF$proportion # urban, regional, remote
names(weights) <- c("urban", "regional", "remote")

weightsClinicDF <- filter(currentTreat, stage == "diagnoses")
weightsClinic <- weightsClinicDF$proportion # urban, regional, remote
names(weightsClinic) <- c("shc", "gp", "other")

# Proportion treated -----------------------------------------------------
# Simply take the mean of the estimates for remote areas
treatedDF <- filter(currentTreat, stage == "treated")

propTreatedUrban <- weightsClinic["gp"] * 
  filter(treatedDF, region == "urban", context == "gp")$proportion + 
  (1 - weightsClinic["gp"]) * 
  filter(treatedDF, region == "urban", context == "other")$proportion

propTreatedRegion <- weightsClinic["gp"] * 
  filter(treatedDF, region == "regional", context == "gp")$proportion + 
  (1 - weightsClinic["gp"]) * 
  filter(treatedDF, region == "regional", context == "other")$proportion

propTreatedRemote <- mean(filter(treatedDF, 
                                 region == "remote")$proportion)

propTreated <- c(propTreatedUrban, propTreatedRegion, propTreatedRemote)
propTreated <- sum(propTreated * weights)

# Hard coded ranges based on propTreated value - +/- 10%
propTreatedMin <- min(filter(treatedDF, 
  region == "remote")$proportion) # minimum in remote
propTreatedMax <- min(1, propTreated * 1.1)

maleDiagnoses <- filter(chlamcascade, stage == "notifications", 
                        sex == "male")
femaleDiagnoses <- filter(chlamcascade, stage == "notifications", 
                        sex == "female")

if (is.na(maleDiagnoses$lower)) {
  # No uncertainty in notifications
  maleTreated <- as.matrix(maleDiagnoses$estimate) %*%
    t(as.matrix(c(propTreated, propTreatedMin, propTreatedMax)))
  
  femaleTreated <- as.matrix(femaleDiagnoses$estimate) %*%
    t(as.matrix(c(propTreated, propTreatedMin, propTreatedMax)))
  
} else {  
  # Uncertainty in notifications
  maleTreated <- t(as.matrix(c(maleDiagnoses$estimate,
                               maleDiagnoses$lower,
                               maleDiagnoses$upper))* 
                     as.matrix(c(propTreated, propTreatedMin,
                                 propTreatedMax)))
  femaleTreated <- t(as.matrix(c(femaleDiagnoses$estimate,
                               femaleDiagnoses$lower,
                               femaleDiagnoses$upper))* 
                     as.matrix(c(propTreated, propTreatedMin,
                                 propTreatedMax)))
}

chlamcascade <- rbind(chlamcascade, 
                  data.frame(stage = "treated",
                             year = rep(resultsYear, 3),
                             sex = rep(c("male", "female", "all"), 
                                       each = length(resultsYear)), 
                             estimate = c(maleTreated[, 1],
                                          femaleTreated[, 1],
                                          maleTreated[, 1] + 
                                            femaleTreated[, 1]),
                             lower =  c(maleTreated[, 2], 
                                        femaleTreated[ , 2],
                                        maleTreated[, 2] + 
                                            femaleTreated[, 2]), 
                             upper = c(maleTreated[, 3], 
                                       femaleTreated[, 3],
                                       maleTreated[, 3] + 
                                            femaleTreated[, 3]),
                             percentprevious = 100 * 
                               c(maleTreated[, 1] / maleDiags,
                                 femaleTreated[, 1] / femaleDiags,
                                 (maleTreated[, 1] + femaleTreated[, 1]) /
                                   (maleDiags + femaleDiags)),
                             percentpreviousLower = 100 * 
                               c(maleTreated[, 2] / upperMaleDiags,
                                 femaleTreated[, 2] / upperFemaleDiags,
                                 (maleTreated[, 2] + femaleTreated[, 2]) / 
                                   (upperMaleDiags + upperFemaleDiags)),
                             percentpreviousUpper = 100 * 
                               c(maleTreated[, 3] / lowerMaleDiags,
                                 femaleTreated[, 3] / lowerFemaleDiags,
                                 (maleTreated[, 3] + femaleTreated[, 3]) /
                                   (lowerMaleDiags + lowerFemaleDiags))))

# Retesting --------------------------------------------------------------
retestDF <- filter(currentTreat, stage == "retested")

# shc, gp, other
diagnosesProp <- filter(currentTreat, stage == "diagnoses")$proportion

# Re-order and add the gp and other together (for non-clinic settings)
# TODO: Think about whether this adding makes sense
diagnosesProp <- c(diagnosesProp[2] + diagnosesProp[3], diagnosesProp[1])
names(diagnosesProp) <- c("gp", "shc")

# Functions for proportion retested
propRetested <- function(gender, value) {
  # Local function to calculate proportion tested
  propReTest <- unname(weights["urban"] * (diagnosesProp["shc"] * 
  filter(retestDF, sex == gender, region == "urban", 
         context == "shc")[value] + 
  diagnosesProp["gp"] * 
  filter(retestDF,  sex == gender, region == "urban", 
         context == "gp")[value]) + 
  weights["regional"] * (diagnosesProp["shc"] * 
  filter(retestDF, sex == gender, region == "regional", 
         context == "shc")[value] + 
  diagnosesProp["gp"] * 
  filter(retestDF,  sex == gender, region == "regional", 
         context == "gp")[value]) + 
  weights["remote"] * (diagnosesProp["shc"] * 
  filter(retestDF, sex == gender, region == "remote", 
         context == "shc")[value] + 
  diagnosesProp["gp"] * 
  filter(retestDF,  sex == gender, region == "remote", 
         context == "gp")[value]))
  
  return(as.numeric(propReTest))
}

propRetestedSHC <- function(gender, value) {
  # Local function to calculate proportion tested
  propReTest <- unname(weights["urban"] *  
  filter(retestDF, sex == gender, region == "urban", 
         context == "shc")[value] + 
  weights["regional"] * 
  filter(retestDF, sex == gender, region == "regional", 
         context == "shc")[value] +
  weights["remote"] *  
  filter(retestDF, sex == gender, region == "remote", 
         context == "shc")[value])
  
  return(as.numeric(propReTest))
}

# Males
propReTestMale <- propRetested("males", "proportion")
propReTestMaleLower <- propRetested("males", "prop_lower")
propReTestMaleUpper <- propRetested("males", "prop_upper") 

# Females
propReTestFemale <- propRetested("females", "proportion")
propReTestFemaleLower <- propRetested("females", "prop_lower")
propReTestFemaleUpper <- propRetested("females", "prop_upper")


if (retestRange) {
  # Period: 42-120 
  retestDFshort <- retests %>%
    filter(period == "42-120", context == "shc") %>%
    select(-period)

  retestDF <- retestDFshort

  propMaleShort <- propRetestedSHC("males", "prop_retested")
  propMaleShortLower <- propRetestedSHC("males", "prop_lower")
  propMaleShortUpper <- propRetestedSHC("males", "prop_upper") 

  propFemaleShort <- propRetestedSHC("females", "prop_retested")
  propFemaleShortLower <- propRetestedSHC("females", "prop_lower")
  propFemaleShortUpper <- propRetestedSHC("females", "prop_upper")
  
  # Period: 7-180
  retestDFlong <- retests %>%
    filter(period == "7-180", context == "shc") %>%
    select(-period)
  
  retestDF <- retestDFlong

  propMaleLong <- propRetestedSHC("males", "prop_retested")
  propMaleLongLower <- propRetestedSHC("males", "prop_lower")
  propMaleLongUpper <- propRetestedSHC("males", "prop_upper") 

  propFemaleLong <- propRetestedSHC("females", "prop_retested")
  propFemaleLongLower <- propRetestedSHC("females", "prop_lower")
  propFemaleLongUpper <- propRetestedSHC("females", "prop_upper")
  
  # Period: 42-180 current
  retestDFcur <- retests %>%
    filter(period == "42-180", context == "shc") %>%
    select(-period)
  
  retestDF <- retestDFcur

  propMaleCur <- propRetestedSHC("males", "prop_retested")
  propMaleCurLower <- propRetestedSHC("males", "prop_lower")
  propMaleCurUpper <- propRetestedSHC("males", "prop_upper") 

  propFemaleCur <- propRetestedSHC("females", "prop_retested")
  propFemaleCurLower <- propRetestedSHC("females", "prop_lower")
  propFemaleCurUpper <- propRetestedSHC("females", "prop_upper")
  
  # Put all proportions into a dataframe
  rangeRetestProp <- data_frame(sex = rep(c("male", "female"), 3),
                                period = rep(c("42-120", "7-180", "42-180"), 
                                             each = 2),
                                year = resultsYear,
                                proportion = c(propMaleShort, 
                                               propFemaleShort,
                                               propMaleLong,
                                               propFemaleLong,
                                               propMaleCur,
                                               propFemaleCur),
                                lower = c(propMaleShortLower, 
                                          propFemaleShortLower,
                                          propMaleLongLower,
                                          propFemaleLongLower,
                                          propMaleCurLower,
                                          propFemaleCurLower),
                                upper = c(propMaleShortUpper, 
                                          propFemaleShortUpper,
                                          propMaleLongUpper,
                                          propFemaleLongUpper,
                                          propMaleCurUpper,
                                          propFemaleCurUpper))
  
}

# Now calculated the number retested
maleRetested <- as.data.frame(t(apply(filter(chlamcascade, 
                                             stage == "treated",
  sex == "male")[, c("estimate", "lower", "upper")], 1, 
  function(x) x * c(propReTestMale, propReTestMaleLower,
                    propReTestMaleUpper))))

femaleRetested <- as.data.frame(t(apply(filter(chlamcascade, 
                                               stage == "treated",
  sex == "female")[, c("estimate", "lower", "upper")], 1, 
  function(x) x * c(propReTestFemale, propReTestFemaleLower,
                    propReTestFemaleUpper))))

if (retestRange) {
  # Period: 42-120 
  maleRetestedShort <- as.data.frame(t(apply(filter(chlamcascade, 
    stage == "treated", sex == "male")[, 
      c("estimate", "lower", "upper")], 1, function(x) x *
      c(propReTestMale * propMaleShort / propMaleCur, 
        propReTestMaleLower * propMaleShortLower / propMaleCurLower,
        propReTestMaleUpper * propMaleShortUpper / propMaleCurUpper))))
  
  femaleRetestedShort <- as.data.frame(t(apply(filter(chlamcascade, 
    stage == "treated", sex == "female")[, 
      c("estimate", "lower", "upper")], 1, function(x) x *
      c(propReTestFemale * propFemaleShort / propFemaleCur, 
        propReTestFemaleLower * propFemaleShortLower / propFemaleCurLower,
        propReTestFemaleUpper * propFemaleShortUpper / propFemaleCurUpper))))
  
  # Period: 7-180
  maleRetestedLong <- as.data.frame(t(apply(filter(chlamcascade, 
    stage == "treated", sex == "male")[, 
      c("estimate", "lower", "upper")], 1, function(x) x *
      c(propReTestMale * propMaleLong / propMaleCur, 
        propReTestMaleLower * propMaleLongLower / propMaleCurLower,
        propReTestMaleUpper * propMaleLongUpper / propMaleCurUpper))))
  
  femaleRetestedLong <- as.data.frame(t(apply(filter(chlamcascade, 
    stage == "treated", sex == "female")[, 
      c("estimate", "lower", "upper")], 1, function(x) x *
      c(propReTestFemale * propFemaleLong / propFemaleCur, 
        propReTestFemaleLower * propFemaleLongLower / propFemaleCurLower,
        propReTestFemaleUpper * propFemaleLongUpper / propFemaleCurUpper))))
  
  # Store and save results 
  maleRetestedShort <- mutate(maleRetestedShort, sex = "male", 
                              period = "42-120", year = resultsYear)
  femaleRetestedShort <- mutate(femaleRetestedShort, sex = "female",
                                period = "42-120", year = resultsYear)
  maleRetestedLong <- mutate(maleRetestedLong, sex = "male", 
                             period = "7-180", year = resultsYear)
  femaleRetestedLong <- mutate(femaleRetestedLong, sex = "female", 
                               period = "7-180", year = resultsYear)
  
  rangeRetesting <- bind_rows(maleRetestedShort, femaleRetestedShort,
                              maleRetestedLong, femaleRetestedLong) %>%
    select(sex, period, year, everything())
  
}  

# Store in our cascade
chlamcascade <- rbind(chlamcascade, 
                      data.frame(stage = "retested",
                                 year = rep(resultsYear, 3),
                                 sex = rep(c("male", "female", "all"), 
                                           each = length(resultsYear)),
                                 estimate = c(maleRetested$estimate,
                                              femaleRetested$estimate,
                                              maleRetested$estimate + 
                                                femaleRetested$estimate),
                                 lower =  c(maleRetested$lower,
                                            femaleRetested$lower,
                                            maleRetested$lower + 
                                              femaleRetested$lower), 
                                 upper = c(maleRetested$upper,
                                           femaleRetested$upper,
                                           maleRetested$upper + 
                                              femaleRetested$upper),
                                 percentprevious = 100 * 
                                   c(maleRetested$estimate / 
                                       maleTreated[, 1],
                                     femaleRetested$estimate /
                                       femaleTreated[, 1],
                                     (maleRetested$estimate +
                                        femaleRetested$estimate) / 
                                       (maleTreated[, 1] + femaleTreated[, 1])),
                                 percentpreviousLower = 100 * 
                                   c(maleRetested$lower/ 
                                       maleTreated[, 3],
                                     femaleRetested$lower /
                                       femaleTreated[, 3],
                                      (maleRetested$lower +
                                        femaleRetested$lower) / 
                                       (maleTreated[, 3] + femaleTreated[, 3])),
                                 percentpreviousUpper = 100 * 
                                   c(maleRetested$upper / 
                                       maleTreated[, 2],
                                     femaleRetested$upper /
                                       femaleTreated[, 2],
                                     (maleRetested$upper +
                                        femaleRetested$upper) / 
                                       (maleTreated[, 2] + 
                                          femaleTreated[, 2]))))

# Retested positive ------------------------------------------------------

if (resultsYear <= 2014) {
  positiveDF <- filter(currentTreat, stage == "positive")
  propPositive <- colSums(positiveDF[, 3:5] * diagnosesProp, na.rm = TRUE)
  propNegative <- 1- sum(propPositive * weights)
  
  # Hard coded ranges based on propNegative value - +/- 10%
  propNegativeMin <- propNegative * 0.9
  propNegativeMax <- min(propNegative * 1.1,1)
  
  maleNegative <- filter(chlamcascade, stage == "retested",
                         sex == "male")$estimate * c(propNegative,
                                                     propNegativeMin,
                                                     propNegativeMax)
  
  femaleNegative <- filter(chlamcascade, stage == "retested",
                           sex == "female")$estimate * c(propNegative,
                                                         propNegativeMin,
                                                         propNegativeMax)
  
  chlamcascade <- rbind(chlamcascade, data.frame(stage = "negative",
                                        year = rep(resultsYear, 2),
                                        sex = c("male", "female"),
                                        estimate = c(maleNegative[1],
                                                     femaleNegative[1]),
                                        lower =  c(maleNegative[2],
                                                   femaleNegative[2]),
                                         upper = c(maleNegative[3],
                                                   femaleNegative[3]),
                        percentprevious = 100 * 
                                   c(maleNegative[1] / 
                                       maleRetested[, 1],
                                     femaleNegative[1] /
                                       femaleRetested[, 1])))
  
  
}

if (saveCascade) {
  
  # Create output figures folder
  dir.create(file.path(basePath, "output", toString(resultsYear)), 
             showWarnings = FALSE)
  resultsFolder <- file.path(basePath, "output", toString(resultsYear))
  
  # Cascade
  saveString <- paste0("chlamydia_cascade-", 
                       toString(tail(resultsYear, 1)), ".csv")
  
  write.csv(chlamcascade, file = file.path(resultsFolder, saveString), 
            row.names = FALSE)
  
  # Range retesting
  if (retestRange) {
    
    # Range in numbers  
    saveStringRange <- paste0("chlamydia_restesting-", 
                              toString(resultsYear), ".csv")
    
    write.csv(rangeRetesting, file = file.path(resultsFolder,
                                               saveStringRange), 
              row.names = FALSE)
    
    # Range in proportion
    saveStringProp<- paste0("chlamydia_restesting_proportion-", 
                              toString(resultsYear), ".csv")
    
    write.csv(rangeRetestProp, file = file.path(resultsFolder,
                                               saveStringProp), 
              row.names = FALSE)
    
  }
}

```

```{r plotcode}
# Default plot specifications
graphics.off()

# Baseline theme for plot variables
source(file.path(Rcode, "PlotOptions.R"), echo=TRUE)

# Setup colours for ASR - not used in the current code
asrcols <- c("males" = "#2C4452", 
             "females" = "#2B97B0") 
```

```{r barchart}
# saveplots <- TRUE

# Create bar chart plot for Chlamydia cascade
stages <- c("infections" = "New infections", 
            "notifications" = "Diagnoses", 
            "treated" = "Received treatment following diagnosis", 
            "retested" = "Completed follow-up")

stagesNeat <- c("infections" = "New \n infections", 
            "notifications" = "Diagnoses", 
            "treated" = "Received \n treatment \n following \n diagnosis",
            "retested" = "Completed \n follow-up")

if (resultsYear == 2014) {
  stages <- c(stages, "negative" = "Negative at re-test")
  stagesNeat <- c(stagesNeat, "negative" = "Negative \n at re-test")
}


# Plot the bar chart -----------------------------------------------------

# First sort out sex as a factor to order the bars
plotcascade <- chlamcascade
plotcascade$sex <- factor(plotcascade$sex, 
                          levels = c("male", "female", "all"))

# Overall cascade
cascadeAll <- filter(plotcascade, year == resultsYear, 
                     sex %in% c("male", "female"))
texty <- cascadeAll$upper
texty[3:4] <- cascadeAll$estimate[3:4]

allCascade <- ggplot(data = filter(cascadeAll, sex %in% c("male", "female")),
                      aes(x = stage, y = estimate, fill = sex)) + 
  geom_bar(position = "dodge", stat = "identity", colour = "black") + 
  geom_errorbar(aes(ymin = lower, ymax = upper), 
                position = position_dodge(width = 0.9),
                width = 0.2, color = "black", size = 1.2) +
  geom_text(aes(label = ifelse(is.na(percentprevious), "",
                  paste0(format(percentprevious, digits = 3), "%")),
                y = texty + 10000),
            position = position_dodge(width = 0.9),
            fontface = "bold",
            size = 2.5) +
  scale_fill_grey(name = "", start = 0.4, end = 0.9,
                    # values = unname(asrcols[c("males", "females")]), 
                    labels = c("Males", "Females"),
                    breaks = c("male", "female"),
                    limits = c("male", "female")) + 
  scale_x_discrete(labels = stagesNeat) +
  ylab("Number of people") + xlab("") +  
  plotOpts 

# Male cascade over 2013-2015
maleCascade <- ggplot(data = filter(cascadeAll, sex == "male"), 
                      aes(x = stage, y = estimate, 
                          fill = factor(year))) + 
  geom_bar(position = "dodge", stat = "identity", colour = "black") + 
  geom_errorbar(aes(ymin = lower, ymax = upper), 
                position = position_dodge(width = 0.9),
                width = 0.2, color = "black", size = 1.2) +
  scale_fill_manual(name = "", values = "#999999") +
  scale_x_discrete(labels = stagesNeat) +
  ylab("Number of people") + xlab("") +  
  plotOpts 

# Female cascade over 2013-2015    
femaleCascade <- ggplot(data = filter(cascadeAll, sex == "female"), 
                      aes(x = stage, y = estimate, 
                          fill = factor(year))) + 
  geom_bar(position = "dodge", stat = "identity", colour = "black") + 
  geom_errorbar(aes(ymin = lower, ymax = upper), 
                position = position_dodge(width = 0.9),
                width = 0.2, color = "black", size = 1.2) +
  scale_fill_manual(name = "", values = "#999999") +
  scale_x_discrete(labels = stagesNeat) +
  ylab("Number of people") + xlab("") +  
  plotOpts

# Overall for 2015
# cascadeAllbar <- cascadeAll %>%
#   group_by(stage) %>%
#   summarise(estimate = sum(estimate),
#             lower = sum(lower),
#             upper = sum(upper)) 

textyAll <- filter(plotcascade, sex == "all")$upper
textyAll[3:4] <- filter(plotcascade, sex == "all")$estimate[3:4]


allCascadeAll <- ggplot(data = filter(plotcascade, sex == "all"),
                      aes(x = stage, y = estimate)) + 
  geom_bar(stat = "identity", 
           fill = "#999999", colour = "black") + 
  geom_errorbar(aes(ymin = lower, ymax = upper),
                width = 0.2, color = "black", size = 1.2) +
  geom_text(aes(label = ifelse(is.na(percentprevious), "",
                  paste0(format(percentprevious, digits = 3), "%")),
                y = textyAll + 20000),
            position = position_dodge(width = 0.9),
            fontface = "bold",
            size = 3.5) +
  scale_x_discrete(labels = stagesNeat) +
  ylab("Number of people") + xlab("") +  
  plotOpts 

   
# Print plot in separate window and save
if (saveplots) {
  # Create output figures folder
  dir.create(file.path(resultsFolder, "figures"), 
             showWarnings = FALSE)
  figFolder <- file.path(resultsFolder, "figures")
  
  ggsave(file.path(figFolder, paste0("chlamcascade-all-", 
                toString(resultsYear), fileType)), 
         plot = allCascade, 
         width = 4, height = 4, dpi = 300)
  
  # ggsave(file.path(figFolder, paste0("chlamcascade-males-", 
  #               toString(resultsYear), ".png")), 
  #        plot = maleCascade, 
  #        width = 7, height = 5, dpi = 300)
  # 
  # ggsave(file.path(figFolder, paste0("chlamcascade-females-", 
  #               toString(resultsYear), ".png")), 
  #        plot = femaleCascade, 
  #        width = 7, height = 5, dpi = 300)
  
  ggsave(file.path(figFolder, paste0("chlamcascade-overall-", 
                toString(resultsYear), fileType)), 
         plot = allCascadeAll, 
         width = 4, height = 4, dpi = 300)
}

```

# Chlamydia diagnosis and care cascade

```{r createTable}
# Create and insert table 
finalTable <- select(chlamcascade, year, stage, sex)
finalTable$estimate <- NA

if (resultsYear == 2014) {
  skip <- 3:4 
} else {
  skip <- 100  
}

for (ii in 1:nrow(finalTable)){
  if (ii %in% skip) {
    finalTable$estimate[ii] <- FormatData(chlamcascade$estimate[ii], 
                                          places = -1)
  } else {
    finalTable$estimate[ii] <- FormatData(chlamcascade$estimate[ii], 
                                           chlamcascade$lower[ii], 
                                           chlamcascade$upper[ii], 
                                          places = -1)
  }
}

# Rename first column
finalTable$stage <- rep(stages, each = 3)

# Rename columns
finalTable <- rename(finalTable, "Cascade stage" = stage, "Sex" = sex, 
                     "Estimate (range)" = estimate)

allTable <- filter(finalTable, year == resultsYear) %>%
  select(-year)

maleTable <- filter(finalTable, Sex == "male") %>%
  select(-Sex) %>%
  spread("Cascade stage", "Estimate (range)") %>%
  rename(Year = year) %>%
  select(Year, 3, 4, 5, 2)
  
  
femaleTable <- filter(finalTable, Sex == "female") %>%
  select(-Sex) %>%
  spread("Cascade stage", "Estimate (range)") %>%
  rename(Year = year) %>%
  select(Year, 3, 4, 5, 2)

```
